import type { HhsCoreStandard } from "../types";

/**
 * HHS Fire Door Assemblies Knowledge Pack
 *
 * These original HHS operational controls help the HHS Compliance
 * Knowledge Engine evaluate fire-door documentation and conditions.
 *
 * They do not reproduce proprietary accreditation requirements or
 * copyrighted NFPA language. Referenced authorities identify regulatory
 * and technical frameworks that may apply. Organizations must confirm
 * applicable editions, interpretations, and local requirements.
 */
export const hhsFireDoorStandards: HhsCoreStandard[] = [
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-001",
    slug: "fire-door-inventory",
    title: "Fire Door Assembly Inventory",
    intent:
      "The organization maintains an accurate inventory of fire-door assemblies requiring inspection, testing, maintenance, and deficiency tracking.",
    description:
      "A complete inventory allows the organization to identify each applicable fire-door assembly, its location, opening identifier, rating, configuration, inspection status, and related corrective actions.",
    requirement:
      "Maintain a current inventory of applicable fire-door assemblies and update it following construction, renovation, replacement, removal, reclassification, or other building changes.",
    surveyorLooksFor: [
      "A current inventory of applicable fire-door assemblies",
      "A unique identifier for each opening",
      "Specific and verifiable door locations",
      "Identification of door type or configuration",
      "Identification of the required rating when applicable",
      "Identification of single-leaf and paired-door assemblies",
      "Inclusion of doors added during construction or renovation",
      "Reconciliation between the inventory and annual inspection records",
      "Removal or retirement of doors that no longer apply",
      "Traceability between each door and related deficiencies",
    ],
    evidenceExamples: [
      "Fire-door inventory",
      "Life-safety drawing",
      "Door schedule",
      "Opening-protective schedule",
      "Annual fire-door inspection report",
      "As-built construction drawing",
      "Fire-door asset list",
      "Construction turnover documentation",
    ],
    commonFindings: [
      "Fire doors are missing from the inventory",
      "Door locations are vague or duplicated",
      "Opening identifiers are inconsistent across reports",
      "New doors are not added following renovation",
      "Removed doors remain on the active inventory",
      "Door ratings are missing or cannot be verified",
      "Inspection reports cannot be reconciled to the inventory",
      "Paired-door assemblies are recorded as unrelated individual doors",
    ],
    keywords: [
      "fire door inventory",
      "fire-rated door",
      "fire door assembly",
      "opening protective",
      "door schedule",
      "door asset",
      "life safety drawing",
      "opening number",
      "fire door location",
      "door rating",
    ],
    aiGuidance:
      "Map system-specific records that identify individual fire-door assemblies. Give higher confidence when each record includes a unique opening identifier, physical location, door configuration, rating, and inspection status. Generic policies do not satisfy this control.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
        notes:
          "Confirm applicability by occupancy type and the current CMS survey framework.",
      },
      {
        authority: "CMS",
        citation: "K211",
        title: "Means of Egress — General",
        notes:
          "CMS guidance has directed certain annual fire-door inspection deficiencies to this tag.",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
        notes:
          "Confirm the edition adopted by CMS and the applicable authority having jurisdiction.",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and update after relevant building changes",
    evidenceRetention:
      "Life of the assembly, including superseded inventories and modification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review and reconciliation with installed assemblies",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-002",
    slug: "annual-fire-door-inspection",
    title: "Annual Fire Door Assembly Inspection and Testing",
    intent:
      "Fire-door assemblies are inspected and tested at required intervals to verify that they remain capable of performing their intended protective function.",
    description:
      "The annual process evaluates the complete assembly, documents observed conditions, identifies deficiencies, and supports timely corrective action and successful reinspection.",
    requirement:
      "Inspect and test applicable fire-door assemblies at least annually and maintain records identifying the opening, inspection date, results, deficiencies, inspector, and corrective-action status.",
    surveyorLooksFor: [
      "Annual inspection of all applicable fire-door assemblies",
      "A documented inspection date",
      "Identification of the person or company performing the inspection",
      "Opening-specific inspection results",
      "Evaluation of the complete door assembly",
      "Identification of failed inspection criteria",
      "Documentation of inaccessible or omitted doors",
      "Corrective action for identified deficiencies",
      "Reinspection following repairs when appropriate",
      "Reconciliation between inspected doors and the active inventory",
    ],
    evidenceExamples: [
      "Annual fire-door inspection report",
      "Fire-door inspection checklist",
      "Electronic inspection export",
      "Inspector qualification record",
      "Door-by-door inspection results",
      "Deficiency report",
      "Repair and reinspection report",
      "Annual inspection completion summary",
    ],
    commonFindings: [
      "The annual inspection is overdue",
      "Inspection records do not identify individual openings",
      "Some inventoried doors are omitted",
      "Inspection criteria are incomplete",
      "Deficiencies are listed without disposition",
      "Failed doors are not reinspected after repair",
      "The report does not identify the inspector",
      "Multiple facilities are combined without clear location identification",
    ],
    keywords: [
      "annual fire door inspection",
      "fire door testing",
      "fire door inspection report",
      "door inspection checklist",
      "NFPA 80 inspection",
      "annual door test",
      "opening inspection",
      "fire door compliance",
      "door deficiency",
      "door reinspection",
    ],
    aiGuidance:
      "Map completed annual inspection records with identifiable openings, dates, results, deficiencies, and inspector information. Blank forms, proposals, invoices, or inspection schedules alone do not demonstrate completion.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "CMS",
        citation: "K211",
        title: "Means of Egress — General",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
    ],
    evidenceFrequency:
      "After initial installation and at least annually thereafter",
    evidenceRetention:
      "Current annual inspection and prior survey-cycle records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, inventory reconciliation, and representative physical inspection",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-003",
    slug: "fire-door-closing-latching",
    title: "Fire Door Closing and Latching",
    intent:
      "Fire doors close completely and latch securely so the opening can resist the passage of fire and smoke as intended.",
    description:
      "The organization evaluates door movement, closing devices, coordinators, active leaves, inactive leaves, latching hardware, and other components affecting complete closure and secure latching.",
    requirement:
      "Maintain each applicable fire-door assembly so all leaves close completely, operate in the correct sequence when required, and positively latch without manual assistance.",
    surveyorLooksFor: [
      "The door closes completely from the open position",
      "The door latches without manual assistance",
      "Self-closing devices operate properly",
      "Automatic-closing devices operate properly",
      "Paired doors close in the correct sequence",
      "Coordinators function when installed",
      "Inactive leaves secure as designed",
      "Hardware does not prevent complete closure",
      "Flooring or thresholds do not obstruct movement",
      "Temporary items do not prevent closing or latching",
    ],
    evidenceExamples: [
      "Annual fire-door inspection report",
      "Door closer adjustment record",
      "Latch repair work order",
      "Coordinator repair report",
      "Paired-door inspection",
      "Corrective-maintenance record",
      "Successful reinspection record",
      "Door replacement documentation",
    ],
    commonFindings: [
      "The door does not latch",
      "The door requires manual assistance to close",
      "The closer is disconnected or improperly adjusted",
      "Paired leaves close in the wrong sequence",
      "The coordinator is damaged or missing",
      "The inactive leaf does not secure",
      "Flooring prevents complete closure",
      "Added hardware interferes with latching",
      "A door is wedged or otherwise held open improperly",
    ],
    keywords: [
      "positive latching",
      "self closing",
      "automatic closing",
      "door closer",
      "door latch",
      "fire door coordinator",
      "paired doors",
      "inactive leaf",
      "door will not latch",
      "door will not close",
    ],
    aiGuidance:
      "Map inspection findings and repair records involving closure, latching, coordinators, closers, inactive leaves, or paired-door sequencing. Successful repair evidence should demonstrate restored closing and latching performance.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
      {
        authority: "The Joint Commission",
        title: "Life Safety and Physical Environment Requirements",
        notes:
          "Confirm the applicable accreditation program and current standard set.",
      },
    ],
    evidenceFrequency:
      "During annual inspection and whenever a closing or latching problem is identified",
    evidenceRetention:
      "Current inspection cycle and related repair and reinspection records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, functional testing, and repair-record review",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-004",
    slug: "fire-door-clearances-alignment",
    title: "Fire Door Clearances and Alignment",
    intent:
      "Fire-door leaves, frames, and related components maintain appropriate alignment and clearances for reliable operation and protective performance.",
    description:
      "The organization evaluates the fit of each door within its frame, including perimeter conditions, meeting edges, bottom clearance, alignment, binding, sagging, and conditions created by flooring or building movement.",
    requirement:
      "Maintain fire-door assemblies with compliant clearances and alignment and correct conditions that prevent proper closure, latching, or protective performance.",
    surveyorLooksFor: [
      "Clearances are evaluated at applicable locations",
      "Door leaves are properly aligned within the frame",
      "Paired-door meeting edges align properly",
      "The door does not bind against the frame or floor",
      "The door is not visibly sagging",
      "Flooring changes have not created excessive or inadequate clearance",
      "Thresholds do not interfere with operation",
      "Warping or physical damage is evaluated",
      "Clearance measurements are documented when a deficiency is suspected",
      "Repairs restore proper fit and operation",
    ],
    evidenceExamples: [
      "Annual fire-door inspection report",
      "Door-clearance measurement record",
      "Hinge repair work order",
      "Frame repair documentation",
      "Door realignment record",
      "Threshold modification record",
      "Door replacement record",
      "Successful reinspection report",
    ],
    commonFindings: [
      "Excessive perimeter clearances",
      "Excessive clearance at meeting edges",
      "Improper bottom clearance",
      "The door binds against flooring",
      "The door leaf is sagging",
      "The frame is damaged or out of alignment",
      "New flooring changes the door clearance",
      "Clearance deficiencies are repaired without documented verification",
    ],
    keywords: [
      "door gap",
      "door clearance",
      "meeting edge",
      "bottom clearance",
      "undercut",
      "door alignment",
      "sagging door",
      "binding door",
      "door frame",
      "threshold",
      "fire door measurement",
    ],
    aiGuidance:
      "Map inspection findings and repair documentation involving clearances, gaps, alignment, frames, hinges, flooring, thresholds, or door sag. Do not infer compliance from photographs unless measurements or clearly documented inspection results are available.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
    ],
    evidenceFrequency:
      "During annual inspection and after relevant repairs or flooring changes",
    evidenceRetention:
      "Current inspection cycle and associated corrective-action records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, measurement, and document review",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-005",
    slug: "fire-door-labels-components",
    title: "Fire Door Labels and Listed Components",
    intent:
      "Fire-door assemblies retain identifiable, compatible, and appropriately listed components needed to support their intended rating and function.",
    description:
      "The organization protects labels from damage or concealment and evaluates the door, frame, glazing, hardware, protection plates, and other components for compatibility with the assembly.",
    requirement:
      "Maintain required labels in a visible and legible condition and ensure that replacement or added components are appropriate for the fire-door assembly.",
    surveyorLooksFor: [
      "Door labels are present when required",
      "Frame labels are present when required",
      "Labels are visible and legible",
      "Labels are not painted over or intentionally concealed",
      "Glazing and glazing components are appropriate",
      "Installed hardware is compatible with the assembly",
      "Protection plates and accessories are evaluated",
      "Replacement components are documented",
      "Field-applied labels are supported by appropriate documentation",
      "The door and frame can be matched to the inventory",
    ],
    evidenceExamples: [
      "Annual fire-door inspection report",
      "Door-label photograph",
      "Door and frame schedule",
      "Product data",
      "Replacement-hardware documentation",
      "Glazing replacement record",
      "Field-labeling documentation",
      "Door replacement record",
    ],
    commonFindings: [
      "Labels are painted over",
      "Labels are missing or illegible",
      "The door label does not match the required opening",
      "The frame label cannot be located",
      "Unapproved glazing is installed",
      "Added hardware is not evaluated for compatibility",
      "Protection plates or accessories obscure required information",
      "Replacement doors lack supporting documentation",
    ],
    keywords: [
      "fire door label",
      "door rating label",
      "frame label",
      "listed door",
      "listed hardware",
      "fire-rated glazing",
      "label painted over",
      "field label",
      "door certification",
      "opening protective label",
    ],
    aiGuidance:
      "Map inspection records, photographs, schedules, and product documentation involving door labels, frame labels, ratings, glazing, hardware, or listed components. A photograph should be linked to a specific opening whenever possible.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
    ],
    evidenceFrequency:
      "During annual inspection and whenever components are replaced or modified",
    evidenceRetention:
      "Life of the assembly for installation and replacement records; inspection records through the current survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection and component-documentation review",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-006",
    slug: "fire-door-holes-modifications-damage",
    title: "Fire Door Damage and Field Modifications",
    intent:
      "Fire-door assemblies remain free of unapproved alterations, physical damage, and penetrations that could reduce their protective performance.",
    description:
      "The organization evaluates holes, fasteners, field-installed hardware, removed hardware, signage, kick-down holders, surface damage, delamination, warping, and other modifications affecting the assembly.",
    requirement:
      "Prevent unapproved field modifications and promptly evaluate and correct holes, damage, penetrations, altered hardware, and other conditions affecting fire-door assemblies.",
    surveyorLooksFor: [
      "No open holes or unprotected penetrations are present",
      "Removed hardware locations are properly addressed",
      "Added signage and attachments are evaluated",
      "Field-installed hardware is appropriate",
      "Door surfaces are free of significant damage",
      "Door leaves are not delaminated or warped",
      "Kick-down holders or similar devices are not improperly installed",
      "Repairs follow an appropriate method",
      "Major modifications receive appropriate evaluation",
      "Completed repairs are reinspected",
    ],
    evidenceExamples: [
      "Annual fire-door inspection report",
      "Door-damage report",
      "Hardware-removal repair record",
      "Field-modification assessment",
      "Door repair work order",
      "Door replacement record",
      "Product documentation",
      "Reinspection report",
    ],
    commonFindings: [
      "Open holes remain after hardware removal",
      "Kick-down door holders are installed",
      "Unapproved surface bolts or locks are added",
      "Signs are attached using inappropriate fasteners",
      "The door face is damaged or delaminated",
      "Unapproved vision panels or glazing changes are present",
      "Repairs are completed without documentation",
      "Field modifications are not evaluated by qualified personnel",
    ],
    keywords: [
      "fire door hole",
      "door modification",
      "field modification",
      "door damage",
      "kick down holder",
      "removed hardware",
      "surface bolt",
      "door penetration",
      "delaminated door",
      "warped door",
      "fire door repair",
    ],
    aiGuidance:
      "Map inspection findings, photographs, work orders, and evaluations involving holes, physical damage, added or removed hardware, signs, glazing changes, or field modifications. Repair evidence should identify the specific opening and final disposition.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
    ],
    evidenceFrequency:
      "During annual inspection and whenever damage or modification is identified",
    evidenceRetention:
      "Current survey cycle and life of the assembly for significant modification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, repair-record review, and closure verification",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-007",
    slug: "fire-door-hold-open-release",
    title: "Fire Door Hold-Open and Release Functions",
    intent:
      "Fire doors held open by approved devices release and close when required without obstruction or delay.",
    description:
      "The organization tests magnetic holders, automatic-closing devices, detection interfaces, releasing mechanisms, and associated fire alarm functions affecting fire-door operation.",
    requirement:
      "Maintain and test approved hold-open and automatic-release arrangements to verify that affected fire doors release, close, and latch under the required activation conditions.",
    surveyorLooksFor: [
      "Hold-open devices are approved for the application",
      "Magnetic holders release as intended",
      "Automatic-closing doors close completely",
      "Released doors latch when required",
      "Detection or fire-alarm interfaces are tested",
      "Doors are not held open using unapproved methods",
      "Closing paths remain unobstructed",
      "Reset and restoration functions are verified",
      "Failures are documented and corrected",
      "Fire-alarm and door-inspection records are reconciled",
    ],
    evidenceExamples: [
      "Annual fire-door inspection report",
      "Magnetic-holder release test",
      "Fire-alarm interface test",
      "Automatic-closing door test",
      "Door-release repair record",
      "Sequence-of-operations matrix",
      "Corrective-action record",
      "Successful reinspection record",
    ],
    commonFindings: [
      "Doors are wedged open",
      "Magnetic holders do not release",
      "Released doors fail to latch",
      "The fire-alarm interface is not tested",
      "Furniture or equipment blocks the closing path",
      "Unapproved hold-open devices are installed",
      "Automatic-closing functions are disabled",
      "Door and alarm reports contain conflicting results",
    ],
    keywords: [
      "fire door hold open",
      "magnetic door holder",
      "door release",
      "automatic closing door",
      "door wedged open",
      "fire alarm interface",
      "smoke detector release",
      "hold-open device",
      "door magnet",
      "automatic release",
    ],
    aiGuidance:
      "Map records involving magnetic holders, automatic-closing devices, door releases, fire-alarm interfaces, or improper hold-open conditions. Give higher confidence when the document records release, closure, and latching results.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
        notes:
          "May apply when the releasing function is controlled by the fire alarm system.",
      },
    ],
    evidenceFrequency:
      "During annual inspection, required fire-alarm testing, and after repairs",
    evidenceRetention:
      "Current inspection cycle and associated fire-alarm and repair records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Functional testing, document review, and physical observation",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-008",
    slug: "fire-door-deficiency-management",
    title: "Fire Door Deficiency Management",
    intent:
      "Fire-door deficiencies are evaluated, prioritized, corrected, reinspected, and formally closed.",
    description:
      "A structured process connects each failed inspection item to an assigned corrective action, interim risk control when needed, repair record, successful reinspection, and verified closure.",
    requirement:
      "Track fire-door deficiencies from identification through risk assessment, repair, reinspection, and verified completion, with escalation of overdue high-risk items.",
    surveyorLooksFor: [
      "Each deficiency is linked to a specific opening",
      "Deficiencies include clear descriptions",
      "Responsible individuals are assigned",
      "Target completion dates reflect risk",
      "Interim measures are considered when appropriate",
      "Repair documentation is retained",
      "Reinspection confirms successful correction",
      "Closure is traceable to the original finding",
      "Overdue deficiencies are escalated",
      "Repeated deficiencies are evaluated for systemic causes",
    ],
    evidenceExamples: [
      "Fire-door deficiency log",
      "Corrective-action tracker",
      "Door repair work order",
      "Contractor service report",
      "Interim mitigation record",
      "Reinspection report",
      "Completion photograph",
      "Closure-verification record",
    ],
    commonFindings: [
      "Deficiencies remain open after the annual inspection",
      "Repairs cannot be linked to specific openings",
      "Work orders are closed without reinspection",
      "No interim action is documented for delayed repairs",
      "Overdue critical deficiencies are not escalated",
      "Completion photographs do not identify the location",
      "The same deficiency recurs annually",
      "The active inventory is not updated after replacement",
    ],
    keywords: [
      "fire door deficiency",
      "door corrective action",
      "door repair",
      "door reinspection",
      "failed fire door",
      "open deficiency",
      "door work order",
      "closure verification",
      "overdue door repair",
      "fire door remediation",
    ],
    aiGuidance:
      "Map records demonstrating the complete deficiency lifecycle: identified opening, failed condition, assigned action, repair, reinspection, and closure. A closed work order without opening-specific verification should receive lower confidence.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "CMS",
        citation: "K211",
        title: "Means of Egress — General",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
    ],
    evidenceFrequency: "Ongoing as deficiencies are identified",
    evidenceRetention:
      "Current survey cycle and according to organizational corrective-action policy",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, work-order reconciliation, physical verification, and reinspection",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-009",
    slug: "fire-door-repair-replacement",
    title: "Fire Door Repair and Replacement",
    intent:
      "Fire-door repairs and replacements preserve or restore the intended performance of the complete assembly.",
    description:
      "The organization evaluates repair methods, replacement doors, frames, hardware, glazing, and related components before returning the opening to normal service.",
    requirement:
      "Use appropriate methods and compatible components when repairing or replacing fire-door assemblies and document final inspection or acceptance before closure.",
    surveyorLooksFor: [
      "The affected opening is clearly identified",
      "The repair method addresses the documented deficiency",
      "Replacement components are appropriate for the assembly",
      "Door and frame ratings remain compatible",
      "Hardware compatibility is evaluated",
      "Glazing changes are evaluated",
      "Required labels remain available",
      "The completed assembly is functionally tested",
      "The inventory is updated when replacement occurs",
      "Final inspection or acceptance is documented",
    ],
    evidenceExamples: [
      "Fire-door repair report",
      "Door replacement record",
      "Product data",
      "Hardware schedule",
      "Contractor service report",
      "Field-labeling documentation",
      "Post-repair inspection",
      "Acceptance documentation",
      "Updated fire-door inventory",
    ],
    commonFindings: [
      "Replacement components are not documented",
      "The repaired door is not reinspected",
      "Door and frame ratings are inconsistent",
      "Replacement hardware interferes with operation",
      "Labels are missing after replacement",
      "The inventory is not updated",
      "Repairs conceal rather than correct the deficiency",
      "Project closeout lacks final acceptance records",
    ],
    keywords: [
      "fire door repair",
      "fire door replacement",
      "replacement hardware",
      "door frame replacement",
      "fire-rated glazing replacement",
      "post-repair inspection",
      "field labeling",
      "door acceptance",
      "door restoration",
      "door contractor",
    ],
    aiGuidance:
      "Map opening-specific repair and replacement records. Look for the original deficiency, work performed, component information, final functional testing, label status, and successful reinspection.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
    ],
    evidenceFrequency:
      "Whenever a fire-door assembly is repaired or replaced",
    evidenceRetention:
      "Life of the assembly for major repair and replacement records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, component verification, and functional inspection",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Door Assemblies",
    code: "HHS-FAC-FD-010",
    slug: "fire-door-program-oversight",
    title: "Fire Door Program Oversight",
    intent:
      "The organization manages fire-door compliance as a coordinated program rather than as an isolated annual inspection.",
    description:
      "Program oversight integrates inventories, annual inspections, routine observations, repairs, construction changes, deficiency trends, contractor performance, and leadership escalation.",
    requirement:
      "Maintain a coordinated fire-door management process that assigns responsibility, monitors performance, evaluates recurring deficiencies, and reports significant risks to appropriate leadership.",
    surveyorLooksFor: [
      "Defined ownership of the fire-door program",
      "A current inventory and inspection schedule",
      "Monitoring of annual completion",
      "Tracking of pass and failure rates",
      "Timely correction of deficiencies",
      "Analysis of recurring failure types",
      "Coordination with construction and renovation",
      "Evaluation of contractor performance",
      "Escalation of overdue or high-risk deficiencies",
      "Leadership awareness of significant unresolved risks",
    ],
    evidenceExamples: [
      "Fire-door management plan",
      "Annual inspection summary",
      "Fire-door compliance dashboard",
      "Deficiency-aging report",
      "Committee meeting minutes",
      "Leadership report",
      "Contractor performance review",
      "Annual program evaluation",
    ],
    commonFindings: [
      "Annual inspection is completed without ongoing follow-up",
      "No individual owns the fire-door program",
      "Failure trends are not analyzed",
      "Construction changes are not incorporated",
      "Overdue deficiencies are not escalated",
      "Repeated failures occur at the same openings",
      "Leadership receives no summary of significant risks",
      "Inspection and repair data are maintained in disconnected systems",
    ],
    keywords: [
      "fire door program",
      "fire door management",
      "door compliance dashboard",
      "annual inspection summary",
      "door deficiency trend",
      "fire door oversight",
      "door program evaluation",
      "door performance",
      "door compliance rate",
      "fire door leadership report",
    ],
    aiGuidance:
      "Map plans, dashboards, summaries, meeting records, and evaluations showing coordinated oversight of fire-door compliance. Individual inspection reports alone do not demonstrate full program governance.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K761",
        title: "Maintenance, Inspection, and Testing of Doors",
      },
      {
        authority: "NFPA",
        citation: "NFPA 80",
        title: "Standard for Fire Doors and Other Opening Protectives",
      },
      {
        authority: "The Joint Commission",
        title: "Life Safety and Physical Environment Requirements",
        notes:
          "Confirm the applicable accreditation program and current standard set.",
      },
    ],
    evidenceFrequency:
      "Ongoing with formal review at least annually",
    evidenceRetention:
      "Current program records and prior survey-cycle evaluation",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Program-document review, performance-data review, and leadership interview",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
];