import type { HhsCoreStandard } from "../types";

/**
 * HHS Fire Alarm Systems Knowledge Pack
 *
 * These are original HHS operational controls used by the HHS
 * Compliance Knowledge Engine to evaluate fire alarm documentation.
 *
 * These controls do not reproduce proprietary accreditation standards
 * or copyrighted code language. Referenced authorities identify the
 * regulatory and technical frameworks that may apply.
 */
export const hhsFireAlarmStandards: HhsCoreStandard[] = [
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-001",
    slug: "fire-alarm-system-inventory",
    title: "Fire Alarm System Inventory",
    intent:
      "The organization maintains a complete and current inventory of the fire alarm system and its associated devices.",
    description:
      "A reliable inventory allows the organization to verify that every required control unit, initiating device, notification appliance, supervisory device, interface, and transmission component is inspected and tested.",
    requirement:
      "Maintain a current fire alarm system inventory that identifies installed equipment, device locations, system associations, and relevant identifying information.",
    surveyorLooksFor: [
      "A current fire alarm device inventory",
      "Identification of all fire alarm control units",
      "Identification of remote annunciators",
      "Identification of initiating devices",
      "Identification of notification appliances",
      "Identification of supervisory devices",
      "Identification of system interfaces",
      "Device locations that can be physically verified",
      "Updates following renovations or system modifications",
      "Alignment between the inventory and testing reports",
    ],
    evidenceExamples: [
      "Fire alarm device inventory",
      "Fire alarm system equipment list",
      "Fire alarm riser diagram",
      "Fire alarm zone map",
      "As-built fire alarm drawings",
      "Sequence-of-operations matrix",
      "Inspection report containing a device inventory",
      "Acceptance-testing documentation",
    ],
    commonFindings: [
      "Testing reports omit installed devices",
      "Device locations are vague or incomplete",
      "New devices are absent from the inventory",
      "Removed devices remain listed",
      "Multiple panels are not included in one consolidated inventory",
      "Drawings do not reflect building renovations",
      "Supervisory or interface devices are not tracked",
    ],
    keywords: [
      "fire alarm inventory",
      "device inventory",
      "device list",
      "fire alarm drawings",
      "as-built drawings",
      "riser diagram",
      "zone map",
      "fire alarm panel",
      "annunciator",
      "initiating device",
      "notification appliance",
      "supervisory device",
      "sequence of operations",
    ],
    aiGuidance:
      "Map documents that identify the installed fire alarm system and individual system components. Give higher confidence when the document includes device type, identifier, location, panel association, and status. A general fire alarm policy without system-specific information does not satisfy this control.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K341",
        title: "Fire Alarm System Installation",
        notes:
          "Confirm the currently applicable CMS survey requirements and adopted code editions.",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
        notes:
          "Confirm the edition adopted by CMS and the applicable authority having jurisdiction.",
      },
      {
        authority: "NFPA",
        citation: "NFPA 70",
        title: "National Electrical Code",
        notes:
          "May apply to electrical installation and wiring requirements.",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and update after system changes",
    evidenceRetention:
      "Life of the system, including superseded drawings and modification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review and comparison with installed equipment",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-002",
    slug: "fire-alarm-inspection-testing",
    title: "Fire Alarm Inspection and Testing",
    intent:
      "The organization verifies that fire alarm system components operate reliably through required inspection and testing.",
    description:
      "Inspection and testing records demonstrate that devices, appliances, controls, interfaces, power supplies, and transmission functions have been evaluated at the required intervals.",
    requirement:
      "Inspect and test fire alarm system components at required intervals and maintain records identifying the equipment tested, test results, deficiencies, and corrective actions.",
    surveyorLooksFor: [
      "Inspection and testing completed at required intervals",
      "Testing of all applicable system components",
      "Device-level test results",
      "Clearly identified test dates",
      "Clearly identified device locations",
      "Identification of the individual or company performing the work",
      "Documentation of failed or deficient components",
      "Corrective action for identified deficiencies",
      "Evidence that omitted devices were subsequently tested",
      "Consistency between the inventory and testing records",
    ],
    evidenceExamples: [
      "Annual fire alarm inspection report",
      "Semiannual fire alarm test report",
      "Initiating-device test results",
      "Notification-appliance test results",
      "Supervisory-device test results",
      "Fire alarm panel test report",
      "Remote annunciator test",
      "System interface test",
      "Corrective-action documentation",
    ],
    commonFindings: [
      "Required testing is overdue",
      "Reports do not identify individual devices",
      "Devices are marked inaccessible without follow-up",
      "Installed devices are omitted from testing",
      "Failed devices remain unresolved",
      "Reports contain duplicate or inconsistent device locations",
      "Testing records do not identify the applicable building",
      "Corrective actions cannot be matched to the original deficiency",
    ],
    keywords: [
      "fire alarm inspection",
      "fire alarm testing",
      "annual fire alarm test",
      "semiannual fire alarm test",
      "device testing",
      "initiating device test",
      "notification appliance test",
      "alarm panel test",
      "NFPA 72 inspection",
      "fire alarm report",
    ],
    aiGuidance:
      "Map completed inspection and testing reports that include dates, identifiable devices, locations, results, and deficiencies. Blank forms, proposals, invoices, or service agreements alone do not prove that testing occurred.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K345",
        title: "Fire Alarm System Testing and Maintenance",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
    ],
    evidenceFrequency:
      "At the inspection and testing intervals required for each component",
    evidenceRetention:
      "Current inspection cycle and prior survey cycle, or longer when required",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, device reconciliation, and physical observation",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-003",
    slug: "fire-alarm-initiation",
    title: "Fire Alarm Initiation Functions",
    intent:
      "Fire alarm initiating devices reliably detect or report conditions requiring activation of the fire alarm system.",
    description:
      "The organization verifies the operation of manual, automatic, supervisory, and other applicable initiating devices throughout the facility.",
    requirement:
      "Maintain and test applicable fire alarm initiating devices and document their location, function, result, and associated corrective action.",
    surveyorLooksFor: [
      "Manual fire alarm boxes operate as intended",
      "Smoke detectors are included in testing",
      "Heat detectors are included in testing",
      "Waterflow devices initiate the appropriate signal",
      "Supervisory devices produce the correct signal",
      "Special detection systems are included where installed",
      "Device activation is received at the correct control unit",
      "Initiating-device locations match the installed system",
      "Defective devices are replaced or repaired",
    ],
    evidenceExamples: [
      "Manual pull-station test results",
      "Smoke-detector test results",
      "Heat-detector test results",
      "Waterflow switch test",
      "Valve tamper supervisory test",
      "Duct detector test",
      "Special detection system test",
      "Device replacement record",
    ],
    commonFindings: [
      "Smoke detectors are omitted from testing",
      "Waterflow testing is not linked to the fire alarm report",
      "Duct detectors are not included",
      "Pull stations are inaccessible",
      "Device locations cannot be verified",
      "Supervisory devices are recorded as alarm devices",
      "Failed initiating devices remain open",
    ],
    keywords: [
      "initiating device",
      "pull station",
      "manual fire alarm box",
      "smoke detector",
      "heat detector",
      "duct detector",
      "waterflow switch",
      "tamper switch",
      "supervisory signal",
      "alarm initiation",
    ],
    aiGuidance:
      "Map device-level testing records involving manual or automatic initiation of fire alarm, supervisory, or trouble signals. Distinguish initiating-device testing from notification-appliance testing.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K342",
        title: "Fire Alarm System Initiation",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
    ],
    evidenceFrequency:
      "At the required interval for each initiating-device type",
    evidenceRetention:
      "Current inspection cycle and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review and observation of representative devices",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-004",
    slug: "fire-alarm-notification",
    title: "Fire Alarm Occupant Notification",
    intent:
      "The fire alarm system provides effective notification to occupants and staff when activation occurs.",
    description:
      "Notification appliances and emergency communication functions are maintained and tested to confirm that required audible, visible, textual, or voice messages are delivered throughout applicable areas.",
    requirement:
      "Maintain and test fire alarm notification appliances and emergency communication functions to confirm proper operation and appropriate coverage.",
    surveyorLooksFor: [
      "Audible notification appliances are tested",
      "Visible notification appliances are tested",
      "Voice communication functions are tested where installed",
      "Notification reaches applicable occupied areas",
      "Appliance locations are documented",
      "Failed appliances are corrected",
      "Temporary changes in occupancy or room use are evaluated",
      "Renovated areas are included in system records",
    ],
    evidenceExamples: [
      "Horn test results",
      "Strobe test results",
      "Speaker test results",
      "Voice evacuation system test",
      "Notification-appliance inventory",
      "Sound-level evaluation",
      "Acceptance-test report",
      "Notification-appliance repair record",
    ],
    commonFindings: [
      "Notification appliances are missing from test reports",
      "Renovated rooms lack appropriate notification",
      "Strobes are obstructed",
      "Speakers or horns are inaudible in certain locations",
      "Failed appliances remain unresolved",
      "Device locations do not match room names",
      "Temporary walls or construction affect notification coverage",
    ],
    keywords: [
      "notification appliance",
      "horn",
      "strobe",
      "speaker",
      "audible notification",
      "visible notification",
      "voice evacuation",
      "occupant notification",
      "emergency communication",
      "fire alarm annunciation",
    ],
    aiGuidance:
      "Map records that demonstrate testing of audible, visible, voice, or other occupant-notification functions. Do not confuse panel annunciators with occupant notification appliances.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K343",
        title: "Fire Alarm System Notification",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
    ],
    evidenceFrequency:
      "At the required interval for each notification function",
    evidenceRetention:
      "Current inspection cycle and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review and observation of representative appliances",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-005",
    slug: "fire-alarm-control-functions",
    title: "Fire Alarm Control and Interface Functions",
    intent:
      "Fire alarm activation initiates required building, fire-protection, and life-safety control functions.",
    description:
      "System interfaces are tested to verify that connected equipment responds appropriately to alarm, supervisory, trouble, and reset conditions.",
    requirement:
      "Identify, maintain, and test required fire alarm control functions and interfaces, including connected life-safety and building systems.",
    surveyorLooksFor: [
      "A current sequence-of-operations matrix",
      "Door release interfaces are tested",
      "Elevator recall interfaces are tested",
      "Smoke-control interfaces are tested where installed",
      "HVAC shutdown or control functions are tested where applicable",
      "Suppression-system interfaces are tested",
      "Remote monitoring transmission is tested",
      "Control functions operate under applicable alarm conditions",
      "Reset and restoration functions are verified",
      "Deficiencies involving interfaces are corrected",
    ],
    evidenceExamples: [
      "Sequence-of-operations matrix",
      "Fire alarm interface test",
      "Door-release test",
      "Elevator-recall test",
      "Smoke-control interface test",
      "HVAC shutdown test",
      "Suppression-system interface test",
      "Remote transmission test",
      "Acceptance-test documentation",
    ],
    commonFindings: [
      "Sequence-of-operations documentation is outdated",
      "Door releases are not included in testing",
      "Elevator recall is tested separately without reconciliation",
      "HVAC shutdown functions are undocumented",
      "Interfaces are marked not tested",
      "System modifications change control functions without updated records",
      "Failed interfaces remain unresolved",
    ],
    keywords: [
      "fire alarm interface",
      "sequence of operations",
      "door release",
      "magnetic door release",
      "elevator recall",
      "smoke control",
      "HVAC shutdown",
      "system interface",
      "control function",
      "remote monitoring",
      "alarm transmission",
    ],
    aiGuidance:
      "Map documents that test the fire alarm system's interaction with doors, elevators, HVAC equipment, smoke control, suppression systems, remote monitoring, or other connected systems. Give higher confidence when expected and actual outcomes are documented.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K344",
        title: "Fire Alarm System Control Functions",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
    ],
    evidenceFrequency:
      "At required intervals and following changes to connected systems",
    evidenceRetention:
      "Current inspection cycle, prior survey cycle, and system modification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review and functional verification",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-006",
    slug: "fire-alarm-deficiency-management",
    title: "Fire Alarm Deficiency Management",
    intent:
      "Fire alarm deficiencies are promptly evaluated, mitigated, corrected, and verified.",
    description:
      "A structured deficiency-management process ensures that unsuccessful tests, impairments, trouble conditions, inaccessible devices, and damaged components do not remain unresolved.",
    requirement:
      "Document and track fire alarm deficiencies from identification through risk assessment, interim mitigation, repair, retesting, and verified closure.",
    surveyorLooksFor: [
      "Deficiencies are clearly identified",
      "Risk is evaluated",
      "Responsible individuals are assigned",
      "Corrective actions have target dates",
      "Interim measures are established when needed",
      "Affected departments are notified when appropriate",
      "Repairs are documented",
      "Successful retesting is documented",
      "Closure can be traced to the original deficiency",
      "Overdue deficiencies are escalated",
    ],
    evidenceExamples: [
      "Fire alarm deficiency log",
      "Failed-device report",
      "Repair work order",
      "Service report",
      "Interim mitigation record",
      "Retest documentation",
      "Corrective-action tracker",
      "Completion verification",
    ],
    commonFindings: [
      "Failed devices remain listed without resolution",
      "Repairs are documented without retesting",
      "Work orders cannot be matched to inspection findings",
      "No interim mitigation is documented",
      "Inaccessible devices are repeatedly excluded",
      "Overdue deficiencies are not escalated",
      "Completion is recorded without supporting evidence",
    ],
    keywords: [
      "fire alarm deficiency",
      "failed device",
      "corrective action",
      "repair",
      "retest",
      "fire alarm work order",
      "open deficiency",
      "interim mitigation",
      "alarm trouble",
      "closure verification",
    ],
    aiGuidance:
      "Map records demonstrating the complete lifecycle of a fire alarm deficiency. A repair invoice alone is insufficient unless it identifies the affected device or condition and shows restoration or successful retesting.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K345",
        title: "Fire Alarm System Testing and Maintenance",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
    ],
    evidenceFrequency: "Ongoing as deficiencies are identified",
    evidenceRetention:
      "Current survey cycle and according to organizational corrective-action policy",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, work-order reconciliation, and closure verification",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-007",
    slug: "fire-alarm-impairment-management",
    title: "Fire Alarm Impairment and Outage Management",
    intent:
      "Fire alarm impairments and outages are managed to protect occupants until the affected system is restored.",
    description:
      "The organization evaluates the impact of an impairment, implements appropriate interim measures, communicates with affected parties, coordinates required notifications, and documents restoration.",
    requirement:
      "Maintain and implement a documented process for managing planned and unplanned fire alarm impairments and outages.",
    surveyorLooksFor: [
      "The affected system and area are identified",
      "The impairment start time is documented",
      "The expected duration is evaluated",
      "The impact on occupants and operations is assessed",
      "Interim protection measures are implemented",
      "Fire-watch needs are evaluated",
      "Required internal and external notifications are completed",
      "Work is coordinated with affected departments",
      "The system is tested before return to service",
      "Restoration time and notifications are documented",
    ],
    evidenceExamples: [
      "Fire alarm impairment permit",
      "Fire alarm outage record",
      "Fire-watch assessment",
      "Fire-watch log",
      "Notification record",
      "Impairment communication",
      "Repair documentation",
      "Restoration test",
      "Return-to-service record",
    ],
    commonFindings: [
      "Impairments are not formally documented",
      "Fire-watch decisions are not supported",
      "Affected departments are not notified",
      "External notifications are omitted",
      "The impairment remains open after restoration",
      "Return-to-service testing is not documented",
      "Planned shutdowns occur without advance risk assessment",
    ],
    keywords: [
      "fire alarm impairment",
      "fire alarm outage",
      "fire watch",
      "system offline",
      "alarm shutdown",
      "impairment permit",
      "temporary protection",
      "return to service",
      "alarm restoration",
      "planned outage",
    ],
    aiGuidance:
      "Map documents involving temporary loss, shutdown, bypass, disablement, or reduced capability of a fire alarm system. Look for impairment duration, affected areas, notifications, interim measures, restoration testing, and formal closure.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K346",
        title: "Fire Alarm System Outage",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
    ],
    evidenceFrequency: "Whenever an impairment or outage occurs",
    evidenceRetention:
      "Current survey cycle and according to organizational impairment policy",
    responsibleRole: "Facilities Director or Safety Officer",
    validationMethod:
      "Document review, staff interview, and restoration verification",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-008",
    slug: "fire-alarm-power-supplies",
    title: "Fire Alarm Power Supplies",
    intent:
      "Fire alarm control equipment and connected devices maintain reliable primary and secondary power.",
    description:
      "The organization maintains fire alarm power supplies, batteries, chargers, circuits, and related equipment so the system remains available during normal and abnormal power conditions.",
    requirement:
      "Inspect, test, maintain, and document fire alarm primary and secondary power supplies and associated trouble-monitoring functions.",
    surveyorLooksFor: [
      "Primary power is available and supervised",
      "Secondary batteries are inspected and tested",
      "Battery condition is documented",
      "Battery replacement dates are tracked",
      "Charging equipment operates properly",
      "Power-supply trouble signals are tested",
      "Remote power supplies are included",
      "Deficiencies are corrected",
      "Replacement batteries meet system requirements",
    ],
    evidenceExamples: [
      "Fire alarm battery test",
      "Battery replacement record",
      "Power-supply inspection",
      "Remote power-supply test",
      "Charger test",
      "Trouble-signal test",
      "Fire alarm preventive-maintenance record",
      "Service report",
    ],
    commonFindings: [
      "Battery age is unknown",
      "Battery testing is not documented",
      "Remote power supplies are omitted",
      "Corrosion or physical damage is present",
      "Battery replacement is overdue",
      "Trouble signals are not tested",
      "Power-supply deficiencies remain unresolved",
    ],
    keywords: [
      "fire alarm battery",
      "secondary power",
      "primary power",
      "battery test",
      "battery replacement",
      "remote power supply",
      "fire alarm charger",
      "power supply trouble",
      "standby power",
      "fire alarm circuit",
    ],
    aiGuidance:
      "Map records involving fire alarm batteries, chargers, primary power, secondary power, remote power supplies, or power trouble conditions. General generator testing should not satisfy this control unless the document specifically evaluates fire alarm power.",
    referencedAuthorities: [
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
      {
        authority: "NFPA",
        citation: "NFPA 70",
        title: "National Electrical Code",
      },
    ],
    evidenceFrequency:
      "At required inspection, testing, and maintenance intervals",
    evidenceRetention:
      "Current inspection cycle and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review and physical inspection of representative equipment",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-009",
    slug: "fire-alarm-monitoring-transmission",
    title: "Fire Alarm Monitoring and Signal Transmission",
    intent:
      "Fire alarm, supervisory, and trouble signals are reliably transmitted to the responsible monitoring location.",
    description:
      "The organization maintains documentation demonstrating that required signals reach the designated monitoring station, fire department communication point, or other approved receiving location.",
    requirement:
      "Test and maintain fire alarm monitoring and transmission functions and document the receipt of alarm, supervisory, and trouble signals.",
    surveyorLooksFor: [
      "The designated monitoring arrangement is documented",
      "Alarm signals transmit successfully",
      "Supervisory signals transmit successfully",
      "Trouble signals transmit successfully",
      "Transmission equipment is tested",
      "Monitoring contact information is current",
      "Communication failures are corrected",
      "Changes in monitoring providers are documented",
      "Required notifications are initiated appropriately",
    ],
    evidenceExamples: [
      "Monitoring agreement",
      "Central-station documentation",
      "Signal-transmission test",
      "Alarm receipt confirmation",
      "Supervisory-signal test",
      "Trouble-signal test",
      "Communication-failure report",
      "Monitoring-provider service report",
    ],
    commonFindings: [
      "Monitoring agreements are expired or unavailable",
      "Trouble signals are not tested",
      "Transmission testing lacks receipt confirmation",
      "Contact information is outdated",
      "Communication failures are not corrected",
      "The monitoring provider cannot identify the facility",
      "Changes in communication technology are not documented",
    ],
    keywords: [
      "fire alarm monitoring",
      "central station",
      "remote supervising station",
      "signal transmission",
      "alarm receipt",
      "supervisory signal",
      "trouble signal",
      "monitoring agreement",
      "communicator",
      "dialer",
    ],
    aiGuidance:
      "Map contracts, test records, and service reports showing that fire alarm signals are transmitted and received. Give higher confidence when alarm, supervisory, and trouble signals are separately identified.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K341",
        title: "Fire Alarm System Installation",
      },
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
    ],
    evidenceFrequency:
      "At required testing intervals and after communication-system changes",
    evidenceRetention:
      "Current agreement and current and prior survey-cycle testing records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review and signal-transmission verification",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Fire Alarm Systems",
    code: "HHS-FAC-FA-010",
    slug: "fire-alarm-system-modifications",
    title: "Fire Alarm System Modifications and Acceptance Testing",
    intent:
      "Fire alarm system changes are reviewed, documented, tested, and accepted before being relied upon for life safety.",
    description:
      "Additions, replacements, programming changes, renovations, and system expansions are incorporated into system documentation and verified through appropriate acceptance activities.",
    requirement:
      "Document fire alarm system modifications and complete applicable review, testing, acceptance, and record updates before the modified system is placed into normal service.",
    surveyorLooksFor: [
      "The scope of the modification is documented",
      "Applicable design documents are available",
      "Required approvals or permits are documented",
      "Acceptance testing is completed",
      "Affected interfaces are tested",
      "Programming changes are documented",
      "Device inventories are updated",
      "Drawings are updated",
      "Deficiencies identified during acceptance are corrected",
      "Final approval or turnover is documented",
    ],
    evidenceExamples: [
      "Fire alarm modification permit",
      "Design drawings",
      "Shop drawings",
      "Programming-change record",
      "Acceptance-test report",
      "Contractor turnover package",
      "Updated device inventory",
      "Updated as-built drawing",
      "Final inspection documentation",
    ],
    commonFindings: [
      "New devices are not added to the inventory",
      "Acceptance testing is incomplete",
      "Programming changes are undocumented",
      "Interfaces are not tested after modifications",
      "Drawings remain outdated",
      "Temporary devices remain installed",
      "Deficiencies remain open at project completion",
    ],
    keywords: [
      "fire alarm modification",
      "acceptance test",
      "fire alarm renovation",
      "system expansion",
      "programming change",
      "new device",
      "fire alarm permit",
      "turnover package",
      "shop drawings",
      "as-built update",
    ],
    aiGuidance:
      "Map project records involving additions, removals, replacements, programming, renovation, or expansion of the fire alarm system. Look for acceptance testing, updated inventories, updated drawings, interface testing, and formal completion.",
    referencedAuthorities: [
      {
        authority: "NFPA",
        citation: "NFPA 72",
        title: "National Fire Alarm and Signaling Code",
      },
      {
        authority: "NFPA",
        citation: "NFPA 70",
        title: "National Electrical Code",
      },
    ],
    evidenceFrequency: "Whenever the fire alarm system is modified",
    evidenceRetention:
      "Life of the system or according to construction-record retention requirements",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, acceptance-test review, and physical verification",
    department: "Facilities",
    domain: "Fire and Life Safety",
    category: "Fire Alarm Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
];