import type { HhsCoreStandard } from "../types";

/**
 * HHS Means of Egress Knowledge Pack
 *
 * These original HHS operational controls help the HHS Compliance
 * Knowledge Engine evaluate exit access, exit enclosures, discharge,
 * corridor conditions, doors, signage, lighting, storage, obstruction,
 * construction impacts, and corrective-action evidence.
 *
 * These controls do not reproduce proprietary accreditation standards
 * or copyrighted NFPA language. Referenced authorities identify
 * regulatory and technical frameworks that may apply. Organizations
 * must confirm adopted editions, occupancy classifications,
 * interpretations, accreditation requirements, and local authority
 * requirements.
 */
export const hhsMeansOfEgressStandards: HhsCoreStandard[] = [
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-001",
    slug: "means-of-egress-inventory",
    title: "Means of Egress Inventory and Documentation",
    intent:
      "The organization maintains accurate documentation of required exit access, exits, exit enclosures, horizontal exits, and exit discharge paths.",
    description:
      "A complete means-of-egress inventory identifies designated exit routes, stair enclosures, exit passageways, horizontal exits, discharge locations, required exit doors, signage, emergency lighting, and areas dependent on specific egress arrangements.",
    requirement:
      "Maintain current documentation of required means-of-egress components and update it following construction, renovation, space-use changes, door changes, compartment changes, or modifications affecting exit access or discharge.",
    surveyorLooksFor: [
      "Required exits are identified",
      "Exit access routes are identified",
      "Exit stairs and enclosures are documented",
      "Horizontal exits are identified when applicable",
      "Exit discharge locations are identified",
      "Required exit doors are included",
      "Exit signs and emergency lighting are represented",
      "Drawings match current facility conditions",
      "Changes are reflected after construction",
      "Egress responsibility is clearly assigned",
    ],
    evidenceExamples: [
      "Life safety drawings",
      "Egress plan",
      "Exit-route map",
      "Fire and smoke compartment drawings",
      "Door inventory",
      "Exit sign inventory",
      "Emergency lighting inventory",
      "Construction turnover documentation",
      "Approved occupancy drawings",
    ],
    commonFindings: [
      "Exit routes differ from current construction",
      "Removed doors remain on drawings",
      "New barriers are not reflected",
      "Exit discharge paths are not documented",
      "Horizontal exits are incorrectly identified",
      "Life safety drawings are outdated",
      "Door identifiers differ between records",
      "No clear ownership exists for egress documentation",
    ],
    keywords: [
      "means of egress",
      "egress inventory",
      "exit route",
      "exit access",
      "exit discharge",
      "life safety drawing",
      "horizontal exit",
      "exit stair",
      "egress plan",
      "exit door inventory",
    ],
    aiGuidance:
      "Map facility-specific drawings, inventories, diagrams, and approved plans identifying exit access, exits, stairs, horizontal exits, exit discharge, doors, signage, and emergency lighting. Generic policies alone do not satisfy this control.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K200",
        title: "Means of Egress Requirements",
        notes:
          "Confirm the applicable CMS occupancy-specific survey form and current requirements.",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and update after changes affecting means of egress",
    evidenceRetention:
      "Life of the facility, including superseded drawings and major modification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Drawing review and reconciliation with current facility conditions",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-002",
    slug: "exit-access-obstruction-control",
    title: "Exit Access Obstruction Control",
    intent:
      "Exit access routes remain continuously available, recognizable, and free from conditions that could delay evacuation.",
    description:
      "The organization monitors corridors, aisles, door approaches, stair access, exit passageways, and discharge routes for storage, equipment, construction materials, furniture, carts, and other obstructions.",
    requirement:
      "Maintain required exit access and exit paths free from unauthorized obstruction, storage, narrowing, locking, or conditions that could impede movement during an emergency.",
    surveyorLooksFor: [
      "Corridors remain clear",
      "Exit doors are readily accessible",
      "Stair doors are unobstructed",
      "Equipment does not reduce required width",
      "Storage does not block exit signs",
      "Construction materials do not obstruct routes",
      "Exit discharge paths remain usable",
      "Temporary obstructions are promptly removed",
      "Repeated obstruction locations are monitored",
      "Staff understand corridor-storage expectations",
    ],
    evidenceExamples: [
      "Environment-of-care rounds",
      "Life safety inspection checklist",
      "Corridor obstruction audit",
      "Photographic inspection record",
      "Corrective work order",
      "Staff education record",
      "Repeat-finding trend report",
      "Leadership rounding documentation",
    ],
    commonFindings: [
      "Carts are stored in required corridors",
      "Equipment blocks exit doors",
      "Furniture narrows the exit route",
      "Construction materials obstruct egress",
      "Exit discharge is blocked",
      "Temporary storage becomes permanent",
      "Repeated findings occur in the same area",
      "Corrective action is not sustained",
    ],
    keywords: [
      "corridor obstruction",
      "blocked exit",
      "egress obstruction",
      "exit access",
      "corridor storage",
      "blocked stair door",
      "exit discharge obstruction",
      "egress width",
      "equipment in corridor",
      "life safety rounds",
    ],
    aiGuidance:
      "Map inspection records, photographs, rounds, work orders, and corrective actions involving blocked exits, corridor storage, reduced egress width, obstructed stairs, or blocked discharge paths. Photographs should identify location and date.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K211",
        title: "Means of Egress — General",
      },
      {
        authority: "CMS",
        citation: "K271",
        title: "Discharge from Exits",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
    ],
    evidenceFrequency:
      "During routine facility rounds and whenever temporary conditions affect egress",
    evidenceRetention:
      "Current survey cycle and related corrective-action records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, photographic verification, and corrective-action review",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-003",
    slug: "exit-door-operation-security",
    title: "Exit Door Operation and Security",
    intent:
      "Exit doors permit safe and reliable egress while maintaining appropriate security and fire-protection functions.",
    description:
      "The organization evaluates exit doors for accessibility, direction of travel, opening force, latching, locking, delayed-egress or access-control operation, hardware condition, signage, and emergency release.",
    requirement:
      "Inspect and maintain exit doors so they remain readily operable from the egress side without prohibited locking, binding, obstruction, or hardware failure.",
    surveyorLooksFor: [
      "Exit doors open from the egress side",
      "Required doors swing in the correct direction",
      "Door hardware operates properly",
      "Locks comply with the approved arrangement",
      "Access-control systems release as required",
      "Delayed-egress systems function properly",
      "Emergency-release devices are identified",
      "Doors do not bind or drag",
      "Doors latch when required",
      "Deficiencies receive corrective action and retesting",
    ],
    evidenceExamples: [
      "Exit-door inspection",
      "Door hardware test",
      "Access-control release test",
      "Delayed-egress test report",
      "Door repair work order",
      "Locking-system approval documentation",
      "Successful retest record",
      "Egress-door inventory",
    ],
    commonFindings: [
      "An exit door is locked against egress",
      "Door hardware does not release",
      "The door binds on the frame or floor",
      "Access control does not release during testing",
      "Delayed-egress signage is missing",
      "Required door swing is incorrect",
      "Repairs are completed without retesting",
      "Security modifications are not reviewed for life safety",
    ],
    keywords: [
      "exit door",
      "locked exit",
      "egress door",
      "door hardware",
      "access control release",
      "delayed egress",
      "panic hardware",
      "door opening force",
      "exit lock",
      "door retest",
    ],
    aiGuidance:
      "Map inspection, testing, repair, and approval records involving exit doors, locks, access control, delayed egress, emergency release, panic hardware, door swing, opening force, or latching.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K222",
        title: "Egress Doors",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
    ],
    evidenceFrequency:
      "During routine inspections and after hardware, locking, or access-control changes",
    evidenceRetention:
      "Current survey cycle and life of the system for approved locking arrangements",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, functional testing, and approval-document review",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-004",
    slug: "exit-signage-visibility",
    title: "Exit Signage and Directional Identification",
    intent:
      "Occupants can readily identify required exits and the direction of egress travel.",
    description:
      "The organization evaluates exit signs, directional signs, visibility, illumination, placement, obstruction, damage, and consistency with approved exit routes.",
    requirement:
      "Maintain required exit and directional signs so they are visible, properly located, illuminated when required, unobstructed, and consistent with the approved means-of-egress arrangement.",
    surveyorLooksFor: [
      "Required exits are identified",
      "Directional signs are provided where needed",
      "Exit signs are visible from the approach",
      "Signs are not obstructed",
      "Illumination is operational",
      "Signs are not damaged",
      "Signs correspond with approved exit routes",
      "Temporary construction signs are accurate",
      "Non-exit doors are not misleading",
      "Failed signs are promptly repaired",
    ],
    evidenceExamples: [
      "Exit-sign inspection log",
      "Emergency lighting and exit-sign test",
      "Life safety rounds",
      "Photographic audit",
      "Exit-sign repair work order",
      "Construction egress plan",
      "Temporary directional-sign inspection",
    ],
    commonFindings: [
      "Exit signs are not illuminated",
      "Signs are blocked by decorations or equipment",
      "Directional signs point toward unavailable routes",
      "Construction changes create misleading signage",
      "Non-exit doors appear to be exits",
      "Exit signs are damaged",
      "Temporary signs remain after construction",
      "Repairs are not verified",
    ],
    keywords: [
      "exit sign",
      "directional exit sign",
      "exit sign inspection",
      "illuminated exit sign",
      "blocked exit sign",
      "egress signage",
      "non exit sign",
      "exit direction",
      "temporary egress sign",
      "exit sign repair",
    ],
    aiGuidance:
      "Map inspection, testing, photographic, repair, and construction records involving exit signs, directional signs, illumination, visibility, obstruction, misleading doors, or temporary egress signage.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K293",
        title: "Exit Signage",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
    ],
    evidenceFrequency:
      "At applicable testing intervals and during routine facility rounds",
    evidenceRetention:
      "Current survey cycle and related repair records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, functional testing, and photographic verification",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "High",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-005",
    slug: "emergency-lighting-egress",
    title: "Emergency Lighting for Means of Egress",
    intent:
      "Means-of-egress paths remain adequately illuminated during loss of normal power.",
    description:
      "The organization evaluates emergency lighting units, battery systems, generator-supplied lighting, transfer operation, illumination duration, test completion, fixture condition, and coverage of required egress paths.",
    requirement:
      "Inspect, test, and maintain emergency lighting serving required means of egress, documenting operation, duration, failures, repairs, and successful retesting.",
    surveyorLooksFor: [
      "Required egress areas have emergency lighting",
      "Emergency lighting activates upon loss of normal power",
      "Battery units are tested",
      "Generator-supplied lighting transfers properly",
      "Required test duration is documented",
      "Fixtures are intact and unobstructed",
      "Dark areas are identified and corrected",
      "Testing records identify the location or asset",
      "Failures receive corrective action",
      "Successful retesting follows repair",
    ],
    evidenceExamples: [
      "Emergency-lighting test log",
      "Battery-unit inspection",
      "Generator transfer test",
      "Illumination survey",
      "Fixture inventory",
      "Emergency-light repair work order",
      "Successful retest documentation",
    ],
    commonFindings: [
      "Emergency lights fail to activate",
      "Battery units do not maintain illumination",
      "Test duration is not documented",
      "Fixtures are missing or damaged",
      "Egress areas remain dark",
      "Testing records do not identify locations",
      "Failed fixtures remain unresolved",
      "Repairs lack documented retesting",
    ],
    keywords: [
      "emergency lighting",
      "egress lighting",
      "battery emergency light",
      "emergency light test",
      "exit illumination",
      "generator lighting",
      "emergency light duration",
      "dark egress path",
      "emergency fixture",
      "emergency light repair",
    ],
    aiGuidance:
      "Map completed test records, inventories, transfer tests, illumination surveys, work orders, and retest records involving emergency lighting serving exit access, exits, stairs, and discharge paths.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K291",
        title: "Emergency Lighting",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
      {
        authority: "NFPA",
        citation: "NFPA 110",
        title:
          "Standard for Emergency and Standby Power Systems",
      },
    ],
    evidenceFrequency:
      "At applicable testing intervals and after repair or system modification",
    evidenceRetention:
      "Current survey cycle and associated repair and retest records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Functional testing, transfer verification, and document review",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-006",
    slug: "exit-enclosure-integrity",
    title: "Exit Enclosure and Stairway Integrity",
    intent:
      "Exit stairs and enclosures remain protected, accessible, and capable of supporting safe evacuation.",
    description:
      "The organization evaluates stair enclosures, exit passageways, doors, penetrations, construction, storage, lighting, signage, handrails, guards, and discharge conditions.",
    requirement:
      "Maintain exit stairs, stair enclosures, and exit passageways free from unauthorized openings, penetrations, storage, damage, and conditions that compromise required protection or safe use.",
    surveyorLooksFor: [
      "Stair enclosures are intact",
      "Stair doors operate properly",
      "Unauthorized penetrations are absent",
      "Storage is not present in exit enclosures",
      "Handrails and guards are secure",
      "Lighting is operational",
      "Stairs are free of trip hazards",
      "Exit passageways remain clear",
      "Discharge doors function properly",
      "Deficiencies receive timely corrective action",
    ],
    evidenceExamples: [
      "Stairwell inspection checklist",
      "Exit-enclosure audit",
      "Barrier inspection",
      "Penetration repair record",
      "Door inspection",
      "Handrail repair work order",
      "Photographic verification",
      "Construction closeout record",
    ],
    commonFindings: [
      "Storage is present in a stair enclosure",
      "Stair doors do not latch",
      "Unsealed penetrations are present",
      "Handrails are loose",
      "Lighting is inadequate",
      "Exit passageways are obstructed",
      "Construction compromises enclosure integrity",
      "Deficiencies recur after correction",
    ],
    keywords: [
      "stair enclosure",
      "exit stair",
      "stairwell inspection",
      "exit passageway",
      "stair storage",
      "stair door",
      "stair penetration",
      "handrail repair",
      "stair lighting",
      "exit enclosure integrity",
    ],
    aiGuidance:
      "Map inspection, barrier, door, construction, repair, and photographic records involving exit stairs, enclosures, passageways, penetrations, storage, handrails, guards, lighting, or discharge doors.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K225",
        title: "Stairways and Smokeproof Enclosures",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
    ],
    evidenceFrequency:
      "During routine life safety rounds and after construction or repair",
    evidenceRetention:
      "Current survey cycle and life of the facility for major enclosure modifications",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, barrier verification, and corrective-action review",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-007",
    slug: "exit-discharge-readiness",
    title: "Exit Discharge Readiness",
    intent:
      "Exit discharge paths safely lead occupants from required exits to a public way or designated safe area.",
    description:
      "The organization evaluates exterior exit doors, sidewalks, ramps, stairs, gates, snow and ice conditions, lighting, drainage, construction barriers, landscaping, and emergency access.",
    requirement:
      "Maintain exit discharge paths so they remain clear, illuminated when required, physically safe, and continuously available under expected weather and operating conditions.",
    surveyorLooksFor: [
      "Exit discharge doors open properly",
      "Exterior paths remain clear",
      "Snow and ice are promptly removed",
      "Exterior lighting is operational",
      "Ramps and stairs are maintained",
      "Gates do not prevent egress",
      "Construction barriers do not block discharge",
      "Drainage does not create hazards",
      "Landscaping does not obstruct routes",
      "Deficiencies are corrected promptly",
    ],
    evidenceExamples: [
      "Exterior egress inspection",
      "Snow and ice removal log",
      "Exterior lighting inspection",
      "Grounds work order",
      "Construction egress plan",
      "Exit discharge photograph",
      "Drainage repair record",
      "Gate inspection",
    ],
    commonFindings: [
      "Snow or ice blocks discharge",
      "Exterior lights are inoperative",
      "Exit doors open into obstructed areas",
      "Construction fencing blocks the route",
      "Gates are locked against egress",
      "Uneven pavement creates trip hazards",
      "Drainage creates standing water or ice",
      "Landscaping narrows the discharge path",
    ],
    keywords: [
      "exit discharge",
      "exterior egress",
      "snow removal exit",
      "blocked discharge",
      "exterior exit lighting",
      "egress sidewalk",
      "exit gate",
      "exit ramp",
      "public way",
      "exterior exit inspection",
    ],
    aiGuidance:
      "Map inspection, grounds, weather-response, lighting, construction, photographic, and repair records involving exterior exit discharge routes, gates, sidewalks, ramps, stairs, snow, ice, drainage, or obstructions.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K271",
        title: "Discharge from Exits",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
    ],
    evidenceFrequency:
      "During routine rounds and more frequently during severe weather or construction",
    evidenceRetention:
      "Current survey cycle and related corrective-action records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, weather-response review, and photographic verification",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-008",
    slug: "temporary-egress-construction",
    title: "Temporary Egress During Construction and Renovation",
    intent:
      "Construction and renovation activities do not create uncontrolled impairment of required means of egress.",
    description:
      "The organization evaluates temporary walls, barriers, equipment, staging, alternate routes, exit signs, lighting, fire alarm coverage, staff communication, and interim life safety measures.",
    requirement:
      "Evaluate and control construction-related impacts on means of egress before work begins and throughout the project, including alternate routes, signage, lighting, barriers, communication, and interim protective measures.",
    surveyorLooksFor: [
      "Egress impacts are assessed before construction",
      "Required routes remain available",
      "Alternate routes are formally approved",
      "Temporary signs are accurate",
      "Emergency lighting supports temporary routes",
      "Barriers do not reduce required width",
      "Staff are notified of route changes",
      "Interim life safety measures are implemented",
      "Daily conditions are monitored",
      "Normal egress is restored at project completion",
    ],
    evidenceExamples: [
      "Preconstruction risk assessment",
      "Interim life safety measures plan",
      "Temporary egress plan",
      "Construction permit",
      "Daily construction inspection",
      "Staff communication",
      "Temporary signage audit",
      "Project closeout inspection",
    ],
    commonFindings: [
      "Construction blocks a required exit",
      "Alternate routes are not approved",
      "Temporary signs are confusing",
      "Emergency lighting does not cover the new route",
      "Barriers narrow the corridor",
      "Staff are unaware of route changes",
      "ILSM requirements are not implemented",
      "Temporary conditions remain after project completion",
    ],
    keywords: [
      "temporary egress",
      "construction exit route",
      "ILSM",
      "interim life safety measures",
      "construction corridor",
      "temporary exit sign",
      "alternate exit route",
      "construction obstruction",
      "egress impairment",
      "renovation egress",
    ],
    aiGuidance:
      "Map construction risk assessments, ILSM plans, temporary egress drawings, inspections, communications, permits, and closeout records involving blocked routes, alternate exits, barriers, temporary signage, or lighting.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K211",
        title: "Means of Egress — General",
      },
      {
        authority: "CMS",
        citation: "K791",
        title: "Construction, Repair, and Improvement Operations",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
      {
        authority: "The Joint Commission",
        title: "Interim Life Safety Measures Requirements",
        notes:
          "Confirm the applicable accreditation program and current standard set.",
      },
    ],
    evidenceFrequency:
      "Before construction begins, throughout affected work, and at project closeout",
    evidenceRetention:
      "Life of the project and current survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Preconstruction review, daily inspection, and project closeout verification",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-009",
    slug: "egress-deficiency-management",
    title: "Means of Egress Deficiency Management",
    intent:
      "Means-of-egress deficiencies are evaluated, prioritized, corrected, verified, and formally closed.",
    description:
      "A structured process connects blocked exits, failed doors, lighting failures, signage issues, stair deficiencies, discharge hazards, and construction impacts to risk assessment, interim controls, repair, verification, and closure.",
    requirement:
      "Track means-of-egress deficiencies from identification through risk assessment, interim mitigation, corrective action, verification, and documented closure, with escalation of overdue or critical conditions.",
    surveyorLooksFor: [
      "Each deficiency identifies the location",
      "The condition is clearly described",
      "Life safety risk is evaluated",
      "A responsible person is assigned",
      "A target completion date is established",
      "Interim measures are implemented when needed",
      "Corrective work is documented",
      "Verification confirms the condition is resolved",
      "Closure is traceable to the original finding",
      "Recurring findings receive systemic evaluation",
    ],
    evidenceExamples: [
      "Egress deficiency log",
      "Corrective-action tracker",
      "Door repair work order",
      "Exit-light repair record",
      "Interim safety measure",
      "Photographic closure evidence",
      "Verification inspection",
      "Root-cause analysis",
    ],
    commonFindings: [
      "Blocked exits remain unresolved",
      "Work orders close without field verification",
      "Critical deficiencies are not escalated",
      "Interim precautions are not documented",
      "Repeat corridor obstructions continue",
      "Repairs are not linked to the original finding",
      "Closed issues remain open in compliance reports",
      "No trend analysis is completed",
    ],
    keywords: [
      "egress deficiency",
      "exit corrective action",
      "blocked exit finding",
      "egress repair",
      "life safety corrective action",
      "exit door repair",
      "egress retest",
      "open egress deficiency",
      "egress remediation",
      "egress root cause",
    ],
    aiGuidance:
      "Map records demonstrating the full deficiency lifecycle: location, condition, risk, interim action, responsibility, repair, verification, and closure. A closed work order without field verification should receive lower confidence.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K211",
        title: "Means of Egress — General",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
    ],
    evidenceFrequency: "Ongoing as deficiencies are identified",
    evidenceRetention:
      "Current survey cycle and according to organizational corrective-action policy",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, physical verification, and closure reconciliation",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Means of Egress",
    code: "HHS-FAC-ME-010",
    slug: "means-of-egress-program-oversight",
    title: "Means of Egress Program Oversight",
    intent:
      "The organization manages means-of-egress readiness as a coordinated life safety program.",
    description:
      "Program oversight integrates drawings, inspections, door performance, corridor conditions, signage, emergency lighting, stair enclosures, exit discharge, construction impacts, deficiencies, trends, and leadership reporting.",
    requirement:
      "Maintain a coordinated means-of-egress management process that assigns responsibility, monitors required conditions, evaluates recurring risks, escalates unresolved deficiencies, and reports significant issues to appropriate leadership.",
    surveyorLooksFor: [
      "Defined ownership of the egress program",
      "Current egress documentation",
      "Routine inspection of exit routes",
      "Monitoring of exit-door performance",
      "Monitoring of emergency lighting and signage",
      "Construction impacts are evaluated",
      "Recurring obstructions are analyzed",
      "High-risk deficiencies are escalated",
      "Corrective actions are verified",
      "Leadership is informed of unresolved risk",
    ],
    evidenceExamples: [
      "Means-of-egress management plan",
      "Life safety dashboard",
      "Egress inspection summary",
      "Deficiency-aging report",
      "Repeated-obstruction trend",
      "Environment-of-care committee minutes",
      "Leadership report",
      "Annual program evaluation",
    ],
    commonFindings: [
      "Egress inspections are inconsistent",
      "No individual owns the program",
      "Door, lighting, and corridor records are not coordinated",
      "Recurring obstructions are not analyzed",
      "Construction impacts are managed informally",
      "Critical deficiencies are not escalated",
      "Corrective actions are not verified",
      "Leadership receives no summary of unresolved risk",
    ],
    keywords: [
      "means of egress program",
      "egress oversight",
      "life safety dashboard",
      "exit compliance program",
      "egress inspection summary",
      "egress program evaluation",
      "exit deficiency trend",
      "egress leadership report",
      "exit readiness",
      "life safety oversight",
    ],
    aiGuidance:
      "Map management plans, dashboards, committee records, inspection summaries, trend reports, and annual evaluations showing coordinated oversight of exit routes, doors, lighting, signage, stairs, discharge, construction impacts, and deficiencies.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K200",
        title: "Means of Egress Requirements",
      },
      {
        authority: "NFPA",
        citation: "NFPA 101",
        title: "Life Safety Code",
      },
      {
        authority: "The Joint Commission",
        title: "Physical Environment and Life Safety Requirements",
        notes:
          "Confirm the applicable accreditation program and current standard set.",
      },
    ],
    evidenceFrequency:
      "Ongoing with formal program evaluation at least annually",
    evidenceRetention:
      "Current program records and prior survey-cycle evaluations",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Program-document review, performance-data evaluation, and leadership interview",
    department: "Facilities",
    domain: "Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
];