import type { HhsCoreStandard } from "../types";

/**
 * HHS Medical Gas and Vacuum Systems Knowledge Pack
 *
 * These original HHS operational controls help the HHS Compliance
 * Knowledge Engine evaluate medical gas, medical-surgical vacuum,
 * waste anesthetic gas disposal, source equipment, alarm, valve,
 * outlet, maintenance, testing, modification, and emergency-response
 * evidence.
 *
 * These controls do not reproduce proprietary accreditation standards
 * or copyrighted NFPA language. Referenced authorities identify
 * regulatory and technical frameworks that may apply. Organizations
 * must confirm adopted editions, interpretations, system categories,
 * equipment classifications, manufacturer instructions, accreditation
 * requirements, and local authority requirements.
 */
export const hhsMedicalGasStandards: HhsCoreStandard[] = [
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-001",
    slug: "medical-gas-system-inventory",
    title: "Medical Gas and Vacuum System Inventory",
    intent:
      "The organization maintains an accurate inventory of medical gas, medical-surgical vacuum, and related source and distribution equipment.",
    description:
      "A complete inventory identifies medical gas and vacuum systems, source equipment, manifolds, bulk storage, compressors, vacuum pumps, dryers, receivers, alarms, valves, outlets, inlets, piping zones, and maintenance responsibility.",
    requirement:
      "Maintain a current inventory of medical gas and vacuum system components and update it following construction, renovation, replacement, relocation, modification, retirement, or change in maintenance responsibility.",
    surveyorLooksFor: [
      "Identification of each medical gas system",
      "Identification of each medical-surgical vacuum system",
      "Identification of source equipment and locations",
      "Identification of manifolds and bulk supply systems",
      "Identification of compressors and vacuum pumps",
      "Identification of master and area alarm panels",
      "Identification of zone valves and service valves",
      "Identification of outlets and inlets by area",
      "Reconciliation between the inventory and testing records",
      "Updates following construction or system modification",
    ],
    evidenceExamples: [
      "Medical gas system inventory",
      "Medical gas equipment asset list",
      "Medical gas riser diagram",
      "Valve inventory",
      "Alarm-panel inventory",
      "Outlet and inlet inventory",
      "Medical gas zone map",
      "As-built drawings",
      "Construction turnover documentation",
    ],
    commonFindings: [
      "Medical gas systems are missing from the inventory",
      "Valve identifiers differ between records",
      "Alarm panels are not included",
      "New outlets are not added after construction",
      "Removed equipment remains active in the inventory",
      "Testing reports cannot be reconciled to individual systems",
      "Piping zones are not clearly identified",
      "Responsibility for shared systems is unclear",
    ],
    keywords: [
      "medical gas inventory",
      "medical vacuum inventory",
      "oxygen system",
      "medical air system",
      "nitrous oxide system",
      "medical gas manifold",
      "medical gas valve",
      "medical gas alarm",
      "medical gas outlet",
      "medical gas riser",
    ],
    aiGuidance:
      "Map facility-specific records identifying medical gas systems, vacuum systems, source equipment, alarms, valves, piping zones, outlets, and inlets. Generic policies, proposals, or manufacturer brochures do not satisfy this control.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K901",
        title: "Fundamentals — Building System Categories",
        notes:
          "Confirm the current CMS occupancy-specific survey form and applicable medical gas requirements.",
      },
      {
        authority: "CMS",
        citation: "K909",
        title:
          "Gas and Vacuum Piped Systems — Information and Warning Signs",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and update after relevant system changes",
    evidenceRetention:
      "Life of the system, including superseded inventories and major modification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review and reconciliation with installed systems",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-002",
    slug: "medical-gas-inspection-testing-maintenance",
    title: "Medical Gas Inspection, Testing, and Maintenance Program",
    intent:
      "Medical gas and vacuum systems are inspected, tested, and maintained through a coordinated program supporting safe and reliable operation.",
    description:
      "The organization maintains a comprehensive program covering source equipment, alarms, valves, outlets, inlets, piping, compressors, pumps, manifolds, bulk systems, filters, dryers, and other applicable components.",
    requirement:
      "Establish and maintain a documented inspection, testing, and maintenance program for medical gas and vacuum systems, including required frequencies, assigned responsibilities, completed work, deficiencies, corrective actions, and retesting.",
    surveyorLooksFor: [
      "A defined medical gas maintenance program",
      "All applicable systems and components are included",
      "Inspection frequencies are identified",
      "Testing frequencies are identified",
      "Preventive-maintenance activities are documented",
      "Qualified personnel perform applicable work",
      "Missed or overdue activities are tracked",
      "Deficiencies are formally documented",
      "Repairs and retesting are completed",
      "Facility leadership reviews system performance",
    ],
    evidenceExamples: [
      "Medical gas maintenance plan",
      "Inspection and testing schedule",
      "Preventive-maintenance records",
      "Vendor service agreement",
      "Completed inspection reports",
      "Compliance calendar",
      "Deficiency log",
      "Annual program evaluation",
    ],
    commonFindings: [
      "Required inspections are overdue",
      "Testing records are incomplete",
      "Some system components are omitted",
      "Reports do not identify the tested equipment",
      "Vendor reports are filed without internal review",
      "Deficiencies are not entered into a tracking process",
      "Repairs are completed without retesting",
      "Maintenance frequencies are inconsistent",
    ],
    keywords: [
      "medical gas inspection",
      "medical gas testing",
      "medical gas maintenance",
      "medical vacuum maintenance",
      "medical gas ITM",
      "oxygen system inspection",
      "medical gas compliance",
      "medical gas service report",
      "medical gas preventive maintenance",
      "NFPA 99 maintenance",
    ],
    aiGuidance:
      "Map completed inspection, testing, and maintenance records that identify the system, equipment, date, activity, result, technician, deficiencies, and final disposition. Blank forms, contracts, invoices, or schedules alone do not demonstrate completed work.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K907",
        title:
          "Gas and Vacuum Systems — Maintenance and Testing Operations",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
      {
        authority: "The Joint Commission",
        title: "Physical Environment Requirements",
        notes:
          "Confirm the applicable accreditation program and current standard set.",
      },
    ],
    evidenceFrequency:
      "At the applicable inspection, testing, and maintenance frequencies for each component",
    evidenceRetention:
      "Current survey cycle and sufficient historical records to demonstrate continued system reliability",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, inventory reconciliation, and representative physical verification",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-003",
    slug: "medical-gas-source-equipment",
    title: "Medical Gas Source Equipment Readiness",
    intent:
      "Medical gas source equipment remains capable of providing dependable supply, pressure, capacity, and redundancy.",
    description:
      "The organization evaluates bulk oxygen systems, cylinder manifolds, reserve supplies, medical air compressors, vacuum pumps, receivers, dryers, regulators, relief devices, control panels, and associated source equipment.",
    requirement:
      "Inspect, test, maintain, and monitor medical gas and vacuum source equipment to verify reliable operation, adequate capacity, required redundancy, acceptable pressure, and proper changeover or reserve operation.",
    surveyorLooksFor: [
      "Source equipment is clearly identified",
      "Primary and reserve supplies are operational",
      "Automatic changeover functions properly",
      "Supply pressure is monitored",
      "Compressors and pumps are maintained",
      "Receivers and dryers are included in maintenance",
      "Filters and regulators are serviced",
      "Control panels and alarms are operational",
      "Leaks and abnormal conditions are corrected",
      "Repairs receive operational verification",
    ],
    evidenceExamples: [
      "Bulk oxygen inspection",
      "Medical gas manifold inspection",
      "Medical air compressor maintenance record",
      "Vacuum pump maintenance record",
      "Reserve supply test",
      "Changeover test report",
      "Pressure-monitoring record",
      "Filter or dryer replacement record",
      "Source-equipment repair and retest record",
    ],
    commonFindings: [
      "Reserve supply is not verified",
      "Manifold changeover is not tested",
      "Medical air compressors are overdue for maintenance",
      "Vacuum pumps are omitted from the maintenance program",
      "Filters or dryers are not replaced as scheduled",
      "Source pressure abnormalities are not investigated",
      "Equipment leaks remain unresolved",
      "Repairs are completed without operational retesting",
    ],
    keywords: [
      "medical gas source",
      "bulk oxygen",
      "oxygen manifold",
      "medical air compressor",
      "medical vacuum pump",
      "reserve oxygen supply",
      "manifold changeover",
      "medical gas pressure",
      "medical gas receiver",
      "medical air dryer",
    ],
    aiGuidance:
      "Map inspection, maintenance, monitoring, and testing records involving bulk supply, manifolds, reserve supply, compressors, pumps, receivers, dryers, regulators, filters, control panels, or source pressure. Give higher confidence when the equipment and final operating status are clearly identified.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K920",
        title: "Gas and Vacuum Systems — Operating Equipment",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency:
      "At applicable inspection, testing, maintenance, and monitoring intervals",
    evidenceRetention:
      "Current survey cycle and life of the equipment for significant replacement and modification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, functional testing, monitoring review, and maintenance-record verification",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-004",
    slug: "medical-gas-master-area-alarms",
    title: "Medical Gas Master and Area Alarm Testing",
    intent:
      "Medical gas and vacuum alarm systems reliably communicate abnormal source, pressure, and system conditions to responsible personnel.",
    description:
      "The organization tests master alarm panels, area alarm panels, local equipment alarms, remote alarm signals, pressure switches, alarm labels, visual indicators, audible indicators, and communication pathways.",
    requirement:
      "Inspect and test medical gas and vacuum alarm systems at applicable intervals and after modification or repair, documenting alarm initiation, annunciation, identification, receipt, restoration, deficiencies, and corrective action.",
    surveyorLooksFor: [
      "Master alarm panels are included in testing",
      "Area alarm panels are included in testing",
      "Alarm signals identify the correct system",
      "Alarm signals identify the correct condition",
      "Visual indicators operate properly",
      "Audible indicators operate properly",
      "Alarm pressure points are evaluated",
      "Remote alarm locations receive required signals",
      "Failed alarms are corrected",
      "Successful retesting follows repair",
    ],
    evidenceExamples: [
      "Medical gas alarm test report",
      "Master alarm inspection",
      "Area alarm inspection",
      "Pressure-switch test",
      "Alarm-panel preventive maintenance",
      "Alarm repair work order",
      "Integrated alarm test",
      "Successful retest documentation",
    ],
    commonFindings: [
      "An alarm panel is omitted from testing",
      "The wrong gas or area is displayed",
      "Audible alarms do not function",
      "Visual indicators are damaged",
      "Alarm pressure settings are not documented",
      "Remote alarm transmission is not verified",
      "Alarm labels are inaccurate",
      "Failed alarms are repaired without retesting",
    ],
    keywords: [
      "medical gas alarm",
      "master alarm panel",
      "area alarm panel",
      "oxygen alarm",
      "medical air alarm",
      "vacuum alarm",
      "medical gas pressure alarm",
      "medical gas annunciator",
      "medical gas alarm test",
      "medical gas alarm repair",
    ],
    aiGuidance:
      "Map records involving medical gas master alarms, area alarms, local alarms, pressure switches, visual indicators, audible indicators, signal transmission, annunciation, or restoration. Give higher confidence when individual panels and alarm conditions are identified.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K908",
        title: "Gas and Vacuum Systems — Inspection and Testing",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency:
      "At applicable testing intervals and after alarm-system modification or repair",
    evidenceRetention:
      "Current survey cycle and associated repair and retest records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Functional testing, alarm-point verification, and document review",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-005",
    slug: "medical-gas-valves-labeling-access",
    title: "Medical Gas Valve Identification and Accessibility",
    intent:
      "Medical gas valves remain correctly identified, accessible, protected, and available for emergency isolation.",
    description:
      "The organization evaluates source valves, service valves, riser valves, zone valves, and emergency shutoff arrangements for identification, labeling, access, security, condition, and correspondence with the areas served.",
    requirement:
      "Maintain medical gas and vacuum valves so they are accessible, correctly identified, protected from unauthorized operation, and traceable to the systems and areas they control.",
    surveyorLooksFor: [
      "Valve boxes are accessible",
      "Valve boxes are not obstructed",
      "Valve labels identify the gas or vacuum service",
      "Valve labels identify the areas served",
      "Valve identifiers match system drawings",
      "Valves are protected from unauthorized operation",
      "Valve-box covers and windows are intact",
      "Valves are free of visible damage or leakage",
      "Staff can identify appropriate emergency valves",
      "Changes are reflected on labels and diagrams",
    ],
    evidenceExamples: [
      "Medical gas valve inventory",
      "Zone-valve inspection log",
      "Valve-box inspection",
      "Valve identification audit",
      "Medical gas zone map",
      "Emergency shutoff procedure",
      "Valve repair work order",
      "Corrected valve label photograph",
    ],
    commonFindings: [
      "A zone-valve box is obstructed",
      "The label does not identify the area served",
      "Valve labels conflict with drawings",
      "A valve box is damaged",
      "Valves are leaking",
      "Unauthorized storage blocks valve access",
      "Staff cannot identify the correct emergency valve",
      "Construction changes are not reflected on valve labels",
    ],
    keywords: [
      "medical gas valve",
      "zone valve",
      "medical gas shutoff",
      "medical gas valve box",
      "oxygen zone valve",
      "medical gas labeling",
      "medical gas valve access",
      "medical gas service valve",
      "medical gas isolation",
      "medical gas zone map",
    ],
    aiGuidance:
      "Map valve inventories, inspection logs, diagrams, photographs, emergency procedures, and repair records involving valve identification, accessibility, service area, condition, isolation, or unauthorized obstruction. Photographs should identify the valve location and date.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K909",
        title:
          "Gas and Vacuum Piped Systems — Information and Warning Signs",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency:
      "During routine facility rounds, system inspections, and after construction or labeling changes",
    evidenceRetention:
      "Current survey cycle and life of the system for valve maps and significant modifications",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, drawing reconciliation, and staff interview",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-006",
    slug: "medical-gas-outlets-inlets",
    title: "Medical Gas Outlets and Vacuum Inlets",
    intent:
      "Medical gas outlets and vacuum inlets remain correctly identified, functional, secure, leak-free, and suitable for clinical use.",
    description:
      "The organization evaluates outlets and inlets for gas-specific connection, labeling, flow or suction performance, leakage, physical condition, mounting security, cleanliness, and unauthorized modification.",
    requirement:
      "Inspect, test, maintain, and repair medical gas outlets and vacuum inlets at applicable intervals and whenever damage, leakage, performance concerns, or construction changes are identified.",
    surveyorLooksFor: [
      "Outlets and inlets are correctly labeled",
      "Connections are gas-specific",
      "Outlets are physically secure",
      "Outlets are free of visible damage",
      "Outlets and inlets do not leak",
      "Flow or suction performance is acceptable",
      "Unused outlets remain properly protected",
      "Damaged components are removed from service",
      "Repairs are completed by qualified personnel",
      "Successful testing follows repair or replacement",
    ],
    evidenceExamples: [
      "Medical gas outlet inspection",
      "Vacuum inlet inspection",
      "Outlet performance test",
      "Leak test report",
      "Outlet repair work order",
      "Outlet replacement record",
      "Clinical concern investigation",
      "Successful post-repair verification",
    ],
    commonFindings: [
      "An outlet is loose or damaged",
      "An outlet is incorrectly labeled",
      "An outlet or inlet leaks",
      "Vacuum suction is inadequate",
      "Outlet flow is outside expected performance",
      "A damaged outlet remains available for use",
      "Repairs lack documented testing",
      "New outlets are used before verification is completed",
    ],
    keywords: [
      "medical gas outlet",
      "oxygen outlet",
      "medical air outlet",
      "vacuum inlet",
      "medical gas leak",
      "outlet flow test",
      "vacuum suction test",
      "medical gas outlet repair",
      "medical gas connection",
      "medical gas terminal unit",
    ],
    aiGuidance:
      "Map inspection, testing, repair, and verification records involving medical gas outlets, terminal units, vacuum inlets, leakage, flow, suction, labeling, connection type, physical damage, or mounting security.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K908",
        title: "Gas and Vacuum Systems — Inspection and Testing",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency:
      "At applicable inspection and testing intervals and after repair, replacement, or modification",
    evidenceRetention:
      "Current survey cycle and associated repair, replacement, and verification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Physical inspection, functional testing, and repair-record review",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-007",
    slug: "medical-gas-modification-verification",
    title: "Medical Gas Construction, Modification, and Verification",
    intent:
      "Medical gas and vacuum system construction and modification are controlled, tested, verified, and accepted before clinical use.",
    description:
      "The organization coordinates design review, shutdown planning, infection-control precautions, contractor qualifications, pressure testing, purging, cross-connection testing, alarm verification, system verification, documentation, and clinical release.",
    requirement:
      "Control medical gas construction, renovation, repair, extension, replacement, and modification through a documented process that includes appropriate testing, independent verification when required, updated documentation, and formal authorization before clinical use.",
    surveyorLooksFor: [
      "Medical gas work is reviewed before installation",
      "Qualified installers perform applicable work",
      "Required permits and shutdown controls are used",
      "Testing is completed before system release",
      "Independent verification is completed when applicable",
      "Cross-connections are evaluated",
      "Gas identity and purity are verified when applicable",
      "Alarm and valve operation are verified",
      "As-built drawings and inventories are updated",
      "The affected system is formally released for clinical use",
    ],
    evidenceExamples: [
      "Medical gas construction permit",
      "Shutdown authorization",
      "Installer qualification documentation",
      "Pressure-test report",
      "Purge documentation",
      "Medical gas verification report",
      "Cross-connection test",
      "Alarm and valve test",
      "As-built drawings",
      "Clinical release authorization",
    ],
    commonFindings: [
      "Medical gas work is completed without formal review",
      "Installer qualifications are not documented",
      "Required verification records are missing",
      "The system is used before testing is complete",
      "Cross-connection testing is not documented",
      "Alarm panels are not updated",
      "Valve labels remain inaccurate after construction",
      "As-built drawings are not revised",
    ],
    keywords: [
      "medical gas construction",
      "medical gas verification",
      "medical gas modification",
      "medical gas installer",
      "medical gas shutdown",
      "cross connection test",
      "medical gas pressure test",
      "medical gas purge",
      "medical gas commissioning",
      "medical gas project",
    ],
    aiGuidance:
      "Map construction, repair, modification, testing, verification, commissioning, shutdown, qualification, and release records involving medical gas or vacuum piping systems. A contractor invoice alone does not demonstrate compliant testing or authorization for clinical use.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K910",
        title: "Gas and Vacuum Piped Systems — Modifications",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency:
      "Whenever medical gas or vacuum systems are installed, modified, repaired, extended, or replaced",
    evidenceRetention:
      "Life of the system, including verification reports, as-built drawings, and major modification records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Project-document review, verification-report review, drawing reconciliation, and release authorization",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-008",
    slug: "medical-gas-emergency-response",
    title: "Medical Gas Failure and Emergency Response",
    intent:
      "The organization maintains a coordinated response for medical gas interruption, source failure, pressure loss, contamination concern, alarm condition, and prolonged outage.",
    description:
      "The response process addresses recognition, communication, clinical escalation, system isolation, alternate supply, equipment assessment, vendor response, patient-care prioritization, restoration, and post-event review.",
    requirement:
      "Maintain and exercise procedures for medical gas or vacuum system failure, source depletion, pressure abnormality, alarm activation, contamination concern, planned shutdown, and safe restoration of affected services.",
    surveyorLooksFor: [
      "Medical gas emergency responsibilities are defined",
      "Clinical notification processes are established",
      "Affected areas and systems can be identified",
      "Appropriate isolation valves can be located",
      "Alternate gas supply options are addressed",
      "Patient-care risks are prioritized",
      "Vendor and supplier contacts are current",
      "Planned shutdowns are formally communicated",
      "Restoration and safety verification are documented",
      "Events receive post-incident review",
    ],
    evidenceExamples: [
      "Medical gas emergency procedure",
      "Medical gas shutdown plan",
      "Emergency contact list",
      "Alternate oxygen supply plan",
      "Utility failure checklist",
      "Medical gas incident report",
      "Clinical notification record",
      "System restoration report",
      "After-action review",
    ],
    commonFindings: [
      "Emergency procedures are outdated",
      "Responsibilities are unclear",
      "Staff cannot identify the appropriate valve",
      "Alternate supply arrangements are incomplete",
      "Clinical departments are not notified of shutdowns",
      "Vendor contact information is inaccurate",
      "Restoration testing is not documented",
      "Medical gas incidents are not formally evaluated",
    ],
    keywords: [
      "medical gas failure",
      "oxygen outage",
      "medical gas shutdown",
      "medical gas emergency",
      "oxygen supply failure",
      "medical air failure",
      "vacuum system failure",
      "medical gas alarm response",
      "alternate oxygen supply",
      "medical gas restoration",
    ],
    aiGuidance:
      "Map policies, shutdown plans, emergency procedures, notifications, incident reports, alternate-supply plans, restoration records, and after-action reviews involving medical gas, oxygen, medical air, vacuum, alarm, pressure, or source failure.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K907",
        title:
          "Gas and Vacuum Systems — Maintenance and Testing Operations",
      },
      {
        authority: "CMS",
        title: "Emergency Preparedness Requirements",
        notes:
          "Confirm the applicable provider-specific emergency preparedness requirements.",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency:
      "Maintain continuously, review at least annually, and evaluate after shutdowns, failures, drills, or system changes",
    evidenceRetention:
      "Current emergency procedures, completed shutdown records, incident records, and prior survey-cycle after-action documentation",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Policy review, staff interview, exercise evaluation, and incident-record review",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-009",
    slug: "medical-gas-deficiency-management",
    title: "Medical Gas Deficiency and Corrective-Action Management",
    intent:
      "Medical gas and vacuum system deficiencies are evaluated, prioritized, corrected, retested, and formally closed.",
    description:
      "A structured process connects failed inspections, alarms, leaks, pressure concerns, damaged outlets, maintenance findings, and construction issues to assigned corrective action, interim controls, repair, successful retesting, and verified closure.",
    requirement:
      "Track medical gas and vacuum deficiencies from identification through risk assessment, interim mitigation, repair, retesting, and verified completion, with escalation of overdue or high-risk conditions.",
    surveyorLooksFor: [
      "Each deficiency identifies the affected system or component",
      "The failed condition is clearly described",
      "Clinical and operational risk is evaluated",
      "A responsible person is assigned",
      "A target completion date is established",
      "Interim controls are implemented when appropriate",
      "Repair documentation is retained",
      "Retesting confirms successful correction",
      "Closure is traceable to the original finding",
      "Recurring deficiencies receive systemic evaluation",
    ],
    evidenceExamples: [
      "Medical gas deficiency log",
      "Corrective-action tracker",
      "Medical gas repair work order",
      "Interim mitigation plan",
      "Outlet removal-from-service record",
      "Vendor service report",
      "Successful retest report",
      "Completion verification",
      "Root-cause analysis",
    ],
    commonFindings: [
      "Failed tests remain unresolved",
      "Repairs cannot be linked to the affected component",
      "Work orders are closed without retesting",
      "Interim clinical precautions are not documented",
      "Critical deficiencies are not escalated",
      "Recurring alarm conditions are not analyzed",
      "Vendor recommendations are not reviewed",
      "Closed deficiencies remain open in compliance reports",
    ],
    keywords: [
      "medical gas deficiency",
      "medical gas corrective action",
      "medical gas repair",
      "medical gas retest",
      "failed medical gas inspection",
      "medical gas finding",
      "oxygen system repair",
      "medical gas remediation",
      "open medical gas deficiency",
      "medical gas root cause",
    ],
    aiGuidance:
      "Map records demonstrating the complete deficiency lifecycle: affected system, failed condition, risk, interim action, responsibility, repair, retest, and closure. A closed work order without successful operational verification should receive lower confidence.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K907",
        title:
          "Gas and Vacuum Systems — Maintenance and Testing Operations",
      },
      {
        authority: "CMS",
        citation: "K908",
        title: "Gas and Vacuum Systems — Inspection and Testing",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency: "Ongoing as deficiencies are identified",
    evidenceRetention:
      "Current survey cycle and according to organizational corrective-action policy",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Document review, work-order reconciliation, operational retesting, and closure verification",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Medical Gas and Vacuum Systems",
    code: "HHS-FAC-MG-010",
    slug: "medical-gas-program-oversight",
    title: "Medical Gas and Vacuum Program Oversight",
    intent:
      "The organization manages medical gas and vacuum readiness as a coordinated utility-safety program rather than as a collection of vendor reports.",
    description:
      "Program oversight integrates inventories, testing schedules, source-equipment performance, alarms, valves, outlets, shutdowns, construction changes, deficiencies, contractor qualifications, risk trends, and leadership reporting.",
    requirement:
      "Maintain a coordinated medical gas and vacuum management process that assigns responsibility, monitors required activities, evaluates system reliability, escalates unresolved risks, and reports significant issues to appropriate leadership.",
    surveyorLooksFor: [
      "Defined ownership of the medical gas program",
      "A current system and equipment inventory",
      "A complete inspection and testing schedule",
      "Monitoring of required maintenance completion",
      "Tracking of alarm, valve, and outlet testing",
      "Tracking of shutdowns and interruptions",
      "Analysis of failures and recurring deficiencies",
      "Coordination with construction and renovation",
      "Escalation of overdue high-risk deficiencies",
      "Leadership awareness of unresolved medical gas risks",
    ],
    evidenceExamples: [
      "Medical gas management plan",
      "Medical gas compliance dashboard",
      "Testing-completion summary",
      "Medical gas deficiency-aging report",
      "Shutdown and interruption summary",
      "Utility committee minutes",
      "Leadership report",
      "Annual program evaluation",
      "Contractor qualification review",
    ],
    commonFindings: [
      "Medical gas reports are filed without internal review",
      "No individual owns the medical gas program",
      "Testing completion is not monitored",
      "Alarm panels or valves are omitted from oversight",
      "Shutdowns are managed inconsistently",
      "Recurring failures are not analyzed",
      "Construction changes are not incorporated",
      "Leadership receives no summary of unresolved risk",
    ],
    keywords: [
      "medical gas program",
      "medical gas management",
      "medical gas compliance dashboard",
      "medical gas oversight",
      "medical gas program evaluation",
      "medical gas testing completion",
      "medical gas reliability",
      "medical gas deficiency trend",
      "medical gas leadership report",
      "medical gas governance",
    ],
    aiGuidance:
      "Map plans, dashboards, summaries, committee records, reliability reviews, and annual evaluations showing coordinated oversight of medical gas and vacuum systems. Individual maintenance reports alone do not demonstrate full program governance.",
    referencedAuthorities: [
      {
        authority: "CMS",
        citation: "K907",
        title:
          "Gas and Vacuum Systems — Maintenance and Testing Operations",
      },
      {
        authority: "CMS",
        citation: "K908",
        title: "Gas and Vacuum Systems — Inspection and Testing",
      },
      {
        authority: "CMS",
        citation: "K909",
        title:
          "Gas and Vacuum Piped Systems — Information and Warning Signs",
      },
      {
        authority: "CMS",
        citation: "K910",
        title: "Gas and Vacuum Piped Systems — Modifications",
      },
      {
        authority: "CMS",
        citation: "K920",
        title: "Gas and Vacuum Systems — Operating Equipment",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
      {
        authority: "The Joint Commission",
        title: "Physical Environment Requirements",
        notes:
          "Confirm the applicable accreditation program and current standard set.",
      },
    ],
    evidenceFrequency:
      "Ongoing with formal program evaluation at least annually",
    evidenceRetention:
      "Current program records and prior survey-cycle evaluations",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Program-document review, performance-data evaluation, and leadership interview",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum Systems",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
];