import type { HhsCoreStandard } from "../types";

/**
 * HHS Healthcare Utility Systems Compliance Knowledge Pack
 *
 * These original HHS operational controls help the HHS Compliance
 * Knowledge Engine evaluate utility-system governance, risk assessment,
 * shutdown planning, interruption response, clinical communication,
 * contingency measures, restoration verification, deficiency management,
 * and program oversight.
 *
 * This knowledge pack is intentionally compliance-focused.
 * It does not create equipment-level CMMS requirements for preventive
 * maintenance scheduling, runtime tracking, parts inventory, labor
 * management, or asset lifecycle administration.
 *
 * These controls do not reproduce proprietary accreditation standards
 * or copyrighted technical standards. Referenced authorities identify
 * regulatory and technical frameworks that may apply. Organizations
 * must confirm current federal, state, local, accreditation, adopted-code,
 * manufacturer, and authority-having-jurisdiction requirements.
 */
export const hhsUtilitySystemsStandards: HhsCoreStandard[] = [
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-001",
    slug: "healthcare-utility-systems-management-program",
    title: "Healthcare Utility Systems Management Program",
    intent:
      "The organization maintains a coordinated program for managing utility systems that support patient care, life safety, infection prevention, clinical operations, and the environment of care.",
    description:
      "The organization defines how healthcare utility systems are identified, risk-assessed, monitored, interrupted, restored, and evaluated. The program addresses clinical impact, system dependencies, emergency response, communication, contingency measures, documentation, and leadership oversight.",
    requirement:
      "Maintain a documented utility systems management program that identifies applicable systems, assigns responsibilities, evaluates operational and patient-care risks, establishes interruption and restoration processes, and supports continued survey readiness.",
    surveyorLooksFor: [
      "Utility systems included in the program are identified",
      "Program responsibilities are assigned",
      "Clinical and operational risks are evaluated",
      "System dependencies are understood",
      "Planned interruption processes are defined",
      "Unplanned failure response is addressed",
      "Communication responsibilities are established",
      "Contingency measures are documented",
      "Restoration verification is required",
      "Leadership oversight is demonstrated",
    ],
    evidenceExamples: [
      "Utility systems management plan",
      "Utility risk assessment",
      "Critical utility inventory",
      "System dependency matrix",
      "Utility interruption procedures",
      "Emergency response plan",
      "Restoration checklist",
      "Environment-of-care committee minutes",
      "Annual program evaluation",
      "Leadership risk report",
    ],
    commonFindings: [
      "The utility management program is incomplete or outdated",
      "Critical systems are omitted",
      "Responsibilities are unclear",
      "Clinical dependencies are not documented",
      "Interruption procedures are fragmented",
      "Restoration criteria are undefined",
      "Recurring failures are not analyzed",
      "Leadership is unaware of unresolved utility risks",
    ],
    keywords: [
      "utility systems management",
      "healthcare utilities",
      "utility management plan",
      "critical utility systems",
      "utility risk assessment",
      "facility utility program",
      "utility interruption",
      "utility restoration",
      "environment of care utilities",
      "utility compliance program",
    ],
    aiGuidance:
      "Map comprehensive program documents that identify utility systems, responsibilities, clinical dependencies, interruption processes, contingency measures, restoration requirements, and oversight. Individual maintenance records alone should not be treated as evidence of a complete utility management program.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Hospital Conditions of Participation",
        notes:
          "Confirm current provider-specific physical environment and emergency preparedness requirements.",
      },
      {
        authority: "The Joint Commission",
        title: "Utility Systems and Physical Environment Requirements",
        notes:
          "Confirm the current accreditation program and applicable requirement set.",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
        notes:
          "Confirm the edition adopted by the authority having jurisdiction.",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and formally evaluate at least annually",
    evidenceRetention:
      "Current program records and prior survey-cycle evaluations",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Program-document review, risk-assessment review, stakeholder interview, and leadership-record review",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Utility Systems Management",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-002",
    slug: "critical-utility-systems-identification",
    title: "Critical Utility Systems Identification",
    intent:
      "The organization identifies utility systems whose failure could affect patient care, life safety, infection prevention, clinical operations, or essential facility functions.",
    description:
      "The organization maintains a facility-specific understanding of critical utility systems, the spaces and services they support, their operational dependencies, and the consequences of interruption.",
    requirement:
      "Maintain a current inventory or matrix identifying critical utility systems, supported departments or functions, major dependencies, expected failure consequences, contingency options, and responsible response roles.",
    surveyorLooksFor: [
      "Critical utility systems are identified",
      "Supported clinical functions are documented",
      "System dependencies are recognized",
      "Failure consequences are evaluated",
      "High-risk systems are prioritized",
      "Contingency options are identified",
      "Responsible roles are assigned",
      "Changes are incorporated into the inventory",
      "New construction is reflected",
      "The inventory aligns with emergency planning",
    ],
    evidenceExamples: [
      "Critical utility systems inventory",
      "Utility dependency matrix",
      "Department impact assessment",
      "Facility risk assessment",
      "System one-line diagrams",
      "Utility distribution drawings",
      "Emergency operations plan appendix",
      "Construction turnover documentation",
      "Room-use change review",
      "Annual inventory validation",
    ],
    commonFindings: [
      "Critical systems are not formally identified",
      "Clinical dependencies are undocumented",
      "The inventory excludes newer systems",
      "Construction changes are not incorporated",
      "Failure consequences are assumed rather than assessed",
      "Contingency options are unclear",
      "Departments do not understand their utility dependencies",
      "Emergency plans do not align with the utility inventory",
    ],
    keywords: [
      "critical utility inventory",
      "utility dependency matrix",
      "healthcare utility risk",
      "critical systems list",
      "utility impact assessment",
      "clinical utility dependency",
      "facility systems inventory",
      "essential utility systems",
      "utility failure consequence",
      "utility risk matrix",
    ],
    aiGuidance:
      "Map facility-specific inventories, matrices, risk assessments, drawings, and planning documents showing which utilities are critical, what they support, and what occurs when they fail. Generic equipment lists without clinical or operational context should receive lower confidence.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Hospital Conditions of Participation",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
      {
        authority: "The Joint Commission",
        title: "Utility Systems and Emergency Management Requirements",
      },
    ],
    evidenceFrequency:
      "Review at least annually and following construction, renovation, system modification, or service change",
    evidenceRetention:
      "Life of the facility for major system documentation and current survey-cycle validation records",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Inventory review, drawing reconciliation, risk-assessment review, and stakeholder interview",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Utility Systems Management",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-003",
    slug: "planned-utility-interruption-management",
    title: "Planned Utility Interruption Management",
    intent:
      "Planned utility interruptions are evaluated, authorized, communicated, controlled, and restored without creating unmanaged patient-care or operational risk.",
    description:
      "The organization uses a structured process for planned shutdowns involving electrical power, water, medical gas, HVAC, steam, communications, sewer, fire protection interfaces, or other utility systems.",
    requirement:
      "Require documented planning and authorization before planned utility interruptions, including affected-area identification, risk assessment, clinical approval, notifications, contingency measures, shutdown control, restoration testing, and formal closure.",
    surveyorLooksFor: [
      "The affected utility and service area are identified",
      "Clinical impact is assessed",
      "The shutdown is authorized",
      "Required departments are notified",
      "Contingency measures are established",
      "Emergency and life-safety impacts are considered",
      "The shutdown sequence is controlled",
      "Restoration criteria are defined",
      "Post-restoration testing is documented",
      "The interruption is formally closed",
    ],
    evidenceExamples: [
      "Utility shutdown request",
      "Planned interruption permit",
      "Clinical impact assessment",
      "Department approval record",
      "Shutdown notification",
      "Contingency plan",
      "Pre-shutdown checklist",
      "Restoration checklist",
      "Post-restoration testing",
      "Completed shutdown record",
    ],
    commonFindings: [
      "Shutdowns occur without formal authorization",
      "Affected departments are not identified",
      "Clinical leadership is not notified",
      "Contingency measures are incomplete",
      "System dependencies are overlooked",
      "Restoration testing is not documented",
      "The shutdown record remains open",
      "Post-event problems are not evaluated",
    ],
    keywords: [
      "planned utility shutdown",
      "utility interruption permit",
      "utility shutdown request",
      "planned outage",
      "shutdown notification",
      "clinical impact assessment",
      "utility isolation",
      "restoration checklist",
      "facility shutdown approval",
      "planned utility interruption",
    ],
    aiGuidance:
      "Map shutdown permits, risk assessments, approvals, notifications, contingency plans, checklists, restoration testing, and closure records. A work order describing the technical task without patient-care impact assessment and restoration evidence should not be considered complete.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Hospital Conditions of Participation",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
      {
        authority: "The Joint Commission",
        title: "Utility Systems and Physical Environment Requirements",
      },
    ],
    evidenceFrequency: "For every applicable planned utility interruption",
    evidenceRetention:
      "Current survey cycle and according to organizational project and shutdown-record retention requirements",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Permit review, approval verification, notification review, restoration-record review, and stakeholder interview",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Utility Interruption Management",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-004",
    slug: "unplanned-utility-failure-response",
    title: "Unplanned Utility Failure Response",
    intent:
      "Unexpected utility failures receive prompt assessment, escalation, contingency action, clinical communication, and verified restoration.",
    description:
      "The organization maintains response procedures for unplanned loss or impairment of electrical power, water, medical gas, HVAC, steam, sewer, communications, fuel, or other essential utilities.",
    requirement:
      "Maintain and implement procedures for recognizing utility failures, determining affected areas, assessing patient-care impact, notifying responsible parties, activating contingency measures, prioritizing restoration, and documenting safe return to service.",
    surveyorLooksFor: [
      "Failure recognition and reporting processes are defined",
      "Affected areas can be identified",
      "Clinical impact is assessed",
      "Escalation responsibilities are clear",
      "Contingency measures are activated",
      "Patient-care restrictions are considered",
      "Leadership communication occurs when warranted",
      "Restoration is prioritized by risk",
      "Safe operation is verified",
      "Significant failures receive after-action review",
    ],
    evidenceExamples: [
      "Utility failure response procedure",
      "Emergency notification record",
      "Incident command documentation",
      "Affected-area assessment",
      "Clinical impact assessment",
      "Contingency activation record",
      "Temporary service log",
      "Restoration verification",
      "Incident report",
      "After-action review",
    ],
    commonFindings: [
      "Staff cannot explain the utility failure response",
      "Affected areas are not clearly identified",
      "Clinical departments receive delayed notification",
      "Temporary controls are undocumented",
      "Patient-care risks are not assessed",
      "Restoration occurs without verification",
      "The duration of the outage is unknown",
      "Significant failures receive no after-action review",
    ],
    keywords: [
      "utility failure",
      "unplanned utility outage",
      "utility emergency response",
      "facility outage response",
      "utility interruption procedure",
      "clinical outage notification",
      "temporary utility service",
      "utility restoration",
      "utility incident report",
      "utility after action",
    ],
    aiGuidance:
      "Map procedures and incident records showing recognition, affected-area identification, clinical assessment, escalation, contingency measures, restoration, and post-event review. A repair record alone does not demonstrate complete failure management.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Emergency Preparedness and Physical Environment Requirements",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
      {
        authority: "The Joint Commission",
        title: "Emergency Management and Utility Systems Requirements",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and document each significant utility failure",
    evidenceRetention:
      "Current survey cycle and according to incident and emergency-management retention requirements",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Procedure review, incident-record review, restoration verification, and stakeholder interview",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Utility Interruption Management",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-005",
    slug: "utility-interruption-clinical-communication",
    title: "Utility Interruption Clinical Communication",
    intent:
      "Clinical and operational departments receive timely, accurate, and actionable information during utility interruptions.",
    description:
      "The organization defines how planned and unplanned utility interruptions are communicated, including the affected service, impacted locations, expected duration, operational restrictions, contingency actions, restoration status, and escalation contacts.",
    requirement:
      "Maintain a communication process for utility interruptions that reaches affected departments, clinical leadership, administration, infection prevention, safety, security, and other stakeholders according to the nature and risk of the event.",
    surveyorLooksFor: [
      "Affected departments are identified",
      "Communication responsibilities are assigned",
      "Messages describe the affected utility",
      "Operational restrictions are communicated",
      "Expected duration is provided when known",
      "Updates occur during extended interruptions",
      "Escalation contacts are available",
      "Restoration is formally communicated",
      "Communication failures are evaluated",
      "Records demonstrate notification occurred",
    ],
    evidenceExamples: [
      "Utility notification procedure",
      "Mass communication message",
      "Department call list",
      "Clinical leadership notification",
      "Incident command communication log",
      "Planned outage notice",
      "Status update message",
      "Restoration notice",
      "Communication escalation record",
      "After-action communication review",
    ],
    commonFindings: [
      "Affected departments are not notified",
      "Messages do not explain operational impact",
      "No updates are provided during prolonged outages",
      "Contact lists are outdated",
      "Restoration is not formally communicated",
      "Clinical staff receive conflicting information",
      "Notification records cannot be produced",
      "Communication problems are not corrected",
    ],
    keywords: [
      "utility outage communication",
      "clinical notification",
      "mass communication outage",
      "utility interruption notice",
      "facility outage message",
      "department notification",
      "utility status update",
      "restoration notification",
      "emergency communication log",
      "utility escalation",
    ],
    aiGuidance:
      "Map policies, notification templates, messages, communication logs, call lists, restoration notices, and after-action reviews. Give higher confidence when records identify recipients, time, affected utility, locations, restrictions, and updates.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Emergency Preparedness Requirements",
      },
      {
        authority: "The Joint Commission",
        title: "Emergency Management and Utility Systems Requirements",
      },
    ],
    evidenceFrequency:
      "For every planned or unplanned interruption requiring departmental notification",
    evidenceRetention:
      "Current survey cycle and according to emergency communication and incident-record policies",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Communication-record review, recipient validation, stakeholder interview, and after-action review",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Utility Communication",
    riskLevel: "High",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-006",
    slug: "domestic-water-interruption-response",
    title: "Domestic Water Interruption Response",
    intent:
      "Loss, reduction, contamination, or impairment of domestic water service is managed to protect patient care, sanitation, infection prevention, and essential operations.",
    description:
      "The organization maintains response procedures for interruption or contamination of potable water, hot water, cold water, plumbing fixtures, or water-dependent clinical and support functions.",
    requirement:
      "Maintain a domestic water interruption response process that addresses affected-area identification, clinical and infection-prevention notification, alternate water sources, sanitation, hand hygiene, food service, sterile processing, dialysis or other water-dependent services, restoration, flushing, and return-to-service approval.",
    surveyorLooksFor: [
      "The affected water service is identified",
      "Clinical and infection-prevention risks are assessed",
      "Alternate water arrangements are available",
      "Hand hygiene needs are addressed",
      "Sanitation and toilet access are evaluated",
      "Food and sterile-processing impacts are considered",
      "Water-dependent clinical services are evaluated",
      "Restoration and flushing requirements are defined",
      "Water quality is verified when necessary",
      "Return to service is documented",
    ],
    evidenceExamples: [
      "Domestic water outage procedure",
      "Water interruption risk assessment",
      "Alternate water supply plan",
      "Clinical notification record",
      "Infection-prevention guidance",
      "Bottled water distribution log",
      "Flushing procedure",
      "Water-quality test results",
      "Restoration checklist",
      "After-action review",
    ],
    commonFindings: [
      "The facility lacks an alternate water plan",
      "Hand hygiene contingencies are unclear",
      "Sterile processing impacts are overlooked",
      "Affected departments are not notified",
      "Flushing is not documented",
      "Water quality is not assessed after contamination concerns",
      "Clinical services resume without approval",
      "The outage response is not reviewed afterward",
    ],
    keywords: [
      "domestic water outage",
      "water interruption",
      "potable water failure",
      "water contamination response",
      "alternate water supply",
      "water outage plan",
      "water flushing",
      "water restoration",
      "healthcare water emergency",
      "water service interruption",
    ],
    aiGuidance:
      "Map water interruption procedures, risk assessments, alternate supply plans, notifications, infection-prevention guidance, flushing records, test results, restoration approvals, and after-action reviews.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Emergency Preparedness and Physical Environment Requirements",
      },
      {
        authority: "CDC",
        title:
          "Guidelines for Environmental Infection Control in Health-Care Facilities",
      },
      {
        authority: "EPA",
        title: "Safe Drinking Water Requirements",
        notes:
          "Confirm local water authority and state public-health requirements.",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and document each significant water interruption or contamination event",
    evidenceRetention:
      "Current survey cycle and according to water-quality, incident, and emergency-management retention requirements",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Procedure review, incident-record review, water-quality documentation review, and stakeholder interview",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Water Utility Management",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-007",
    slug: "sewer-drainage-interruption-response",
    title: "Sewer and Drainage Interruption Response",
    intent:
      "Sewer backups, drainage failures, and wastewater interruptions are managed to protect patients, staff, clinical operations, and the care environment.",
    description:
      "The organization maintains procedures for sanitary sewer failure, drain backup, wastewater release, plumbing overflow, blocked drainage, and other conditions that may create contamination or operational hazards.",
    requirement:
      "Maintain a response process that addresses containment, affected-area control, clinical notification, infection-prevention consultation, environmental cleaning, alternate sanitation arrangements, repair, verification, and safe reopening.",
    surveyorLooksFor: [
      "Sewer and drainage failures are promptly reported",
      "Affected areas are controlled",
      "Patient and staff exposure is minimized",
      "Infection prevention is notified",
      "Environmental cleaning is coordinated",
      "Alternate sanitation arrangements are considered",
      "Contaminated materials are managed",
      "The source of failure is corrected",
      "The area is verified before reopening",
      "Significant events receive review",
    ],
    evidenceExamples: [
      "Sewer backup response procedure",
      "Wastewater incident report",
      "Affected-area closure record",
      "Infection-prevention consultation",
      "Environmental cleaning documentation",
      "Alternate restroom plan",
      "Repair documentation",
      "Environmental verification",
      "Reopening approval",
      "After-action review",
    ],
    commonFindings: [
      "The affected area remains open during contamination",
      "Infection prevention is not consulted",
      "Environmental cleaning is undocumented",
      "Alternate restroom access is not arranged",
      "Contaminated materials are mishandled",
      "The area reopens before verification",
      "The source of the backup is not evaluated",
      "Recurring drainage failures are not trended",
    ],
    keywords: [
      "sewer backup",
      "drainage failure",
      "wastewater incident",
      "plumbing overflow",
      "sanitary sewer interruption",
      "sewage response",
      "drain backup healthcare",
      "wastewater contamination",
      "sewer outage procedure",
      "drainage restoration",
    ],
    aiGuidance:
      "Map sewer or drainage response procedures, incident reports, area controls, infection-prevention consultation, cleaning records, repairs, reopening verification, and after-action reviews.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Physical Environment Requirements",
      },
      {
        authority: "CDC",
        title:
          "Guidelines for Environmental Infection Control in Health-Care Facilities",
      },
      {
        authority: "OSHA",
        title: "Occupational Exposure and Sanitation Requirements",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and document each significant sewer or drainage event",
    evidenceRetention:
      "Current survey cycle and according to incident and environmental-cleaning record policies",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Procedure review, incident-record review, cleaning-record review, and reopening-verification review",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Wastewater Utility Management",
    riskLevel: "High",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-008",
    slug: "steam-heating-utility-interruption",
    title: "Steam and Heating Utility Interruption Response",
    intent:
      "Loss of steam or heating service is managed to protect patient care, environmental conditions, sterilization, hot water, and other dependent operations.",
    description:
      "The organization evaluates the consequences of steam, boiler, heating hot water, or related heating utility interruptions and implements risk-based contingency measures.",
    requirement:
      "Maintain procedures for steam or heating interruption that address affected services, environmental conditions, sterilization dependencies, domestic hot-water impacts, temporary measures, clinical communication, restoration, and return-to-service verification.",
    surveyorLooksFor: [
      "Steam and heating dependencies are identified",
      "Affected departments are notified",
      "Patient-care environmental risks are evaluated",
      "Sterilization impacts are considered",
      "Domestic hot-water impacts are assessed",
      "Temporary heating measures are controlled",
      "Fire and electrical risks are considered",
      "Restoration is prioritized",
      "Safe operation is verified",
      "Prolonged events receive leadership oversight",
    ],
    evidenceExamples: [
      "Steam interruption procedure",
      "Heating outage plan",
      "Department impact matrix",
      "Clinical notification record",
      "Sterile-processing contingency plan",
      "Temporary heating assessment",
      "Environmental monitoring log",
      "Restoration checklist",
      "Return-to-service verification",
      "After-action review",
    ],
    commonFindings: [
      "Steam-dependent services are not identified",
      "Sterile processing is not included in the plan",
      "Temporary heaters are used without risk controls",
      "Patient-area temperatures are not monitored",
      "Hot-water impacts are overlooked",
      "Departments receive delayed notification",
      "Restoration lacks verification",
      "Prolonged outages are not escalated",
    ],
    keywords: [
      "steam outage",
      "heating interruption",
      "boiler failure response",
      "heating utility outage",
      "steam interruption plan",
      "temporary heating healthcare",
      "sterilizer steam loss",
      "hot water interruption",
      "heating restoration",
      "steam utility failure",
    ],
    aiGuidance:
      "Map steam and heating interruption procedures, dependency matrices, notifications, environmental monitoring, sterilization contingencies, temporary heating assessments, restoration checklists, and after-action reviews.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Physical Environment and Emergency Preparedness Requirements",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
      {
        authority: "The Joint Commission",
        title: "Utility Systems Requirements",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and document each significant steam or heating interruption",
    evidenceRetention:
      "Current survey cycle and according to incident and emergency-management policies",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Procedure review, environmental-monitoring review, dependency analysis, and incident-record review",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Thermal Utility Management",
    riskLevel: "High",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-009",
    slug: "normal-electrical-power-interruption",
    title: "Normal Electrical Power Interruption Response",
    intent:
      "Loss of normal electrical service is managed through coordinated assessment, emergency-power verification, clinical communication, operational prioritization, and safe restoration.",
    description:
      "The organization distinguishes loss of normal electrical power from emergency-power performance and maintains procedures for identifying affected loads, verifying emergency-system status, managing unsupported equipment, communicating limitations, and restoring normal service.",
    requirement:
      "Maintain procedures for normal electrical power interruption that address emergency-power transfer status, affected clinical and support loads, equipment not supported by emergency power, communication, temporary measures, restoration sequencing, and post-restoration verification.",
    surveyorLooksFor: [
      "Loss of normal power is promptly recognized",
      "Emergency-power status is verified",
      "Unsupported systems are identified",
      "Clinical departments are notified",
      "Patient-care priorities are established",
      "Temporary power use is controlled",
      "Sensitive equipment is considered",
      "Restoration sequencing is defined",
      "Normal operation is verified",
      "Significant events receive review",
    ],
    evidenceExamples: [
      "Normal power outage procedure",
      "Emergency transfer verification",
      "Affected-load assessment",
      "Clinical notification record",
      "Temporary power authorization",
      "Sensitive-equipment response procedure",
      "Electrical restoration checklist",
      "Post-restoration inspection",
      "Utility company communication",
      "After-action review",
    ],
    commonFindings: [
      "Staff assume all systems are on emergency power",
      "Unsupported clinical equipment is not identified",
      "Emergency transfer status is not verified",
      "Clinical departments receive incomplete information",
      "Temporary cords or generators are used without control",
      "Sensitive equipment is reset by unauthorized personnel",
      "Restoration sequencing is undocumented",
      "No post-event verification occurs",
    ],
    keywords: [
      "normal power outage",
      "electrical utility interruption",
      "commercial power failure",
      "normal electrical service loss",
      "emergency transfer verification",
      "unsupported electrical loads",
      "temporary power healthcare",
      "electrical restoration",
      "utility power outage",
      "hospital power interruption",
    ],
    aiGuidance:
      "Map normal-power outage procedures, emergency-transfer verification, affected-load assessments, notifications, temporary-power controls, restoration checklists, and after-action reviews. Distinguish these records from generator testing and emergency-power maintenance evidence.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Emergency Preparedness and Physical Environment Requirements",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
      {
        authority: "NFPA",
        citation: "NFPA 110",
        title: "Standard for Emergency and Standby Power Systems",
      },
    ],
    evidenceFrequency:
      "Maintain continuously and document each significant normal-power interruption",
    evidenceRetention:
      "Current survey cycle and according to electrical incident and emergency-management policies",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Procedure review, outage-record review, transfer-status verification, and restoration-document review",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Electrical Utility Management",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-010",
    slug: "temporary-utility-supply-control",
    title: "Temporary Utility Supply Control",
    intent:
      "Temporary utility arrangements are evaluated, authorized, installed, monitored, and removed without creating unmanaged clinical, life-safety, infection-prevention, or operational risk.",
    description:
      "Temporary electrical power, water, heating, cooling, ventilation, medical gas, compressed air, communications, or other substitute utility arrangements are controlled through documented risk assessment and approval.",
    requirement:
      "Require documented review and authorization before implementing temporary utility supplies, including capacity, compatibility, infection-control impact, life-safety impact, routing, protection, monitoring, duration, inspection, and removal.",
    surveyorLooksFor: [
      "The temporary utility need is documented",
      "Capacity and compatibility are evaluated",
      "Clinical risks are assessed",
      "Life-safety impacts are considered",
      "Infection-control impacts are addressed",
      "Routing and physical protection are appropriate",
      "The arrangement is authorized",
      "Monitoring responsibilities are assigned",
      "The duration is controlled",
      "Removal and restoration are documented",
    ],
    evidenceExamples: [
      "Temporary utility authorization",
      "Risk assessment",
      "Temporary power plan",
      "Temporary HVAC plan",
      "Temporary water plan",
      "Infection-control review",
      "Life-safety review",
      "Inspection log",
      "Monitoring record",
      "Removal and restoration record",
    ],
    commonFindings: [
      "Temporary utilities are installed without approval",
      "Capacity is not verified",
      "Extension cords create hazards",
      "Temporary equipment obstructs egress",
      "Infection-control impacts are ignored",
      "Monitoring is not assigned",
      "Temporary arrangements remain indefinitely",
      "Removal is not documented",
    ],
    keywords: [
      "temporary utility",
      "temporary power",
      "temporary HVAC",
      "temporary water supply",
      "temporary utility plan",
      "utility contingency equipment",
      "temporary electrical service",
      "temporary cooling",
      "temporary heating",
      "temporary utility authorization",
    ],
    aiGuidance:
      "Map temporary utility plans, risk assessments, approvals, infection-control reviews, life-safety reviews, inspection logs, monitoring records, and removal documentation. Equipment rental records alone do not demonstrate safe implementation.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Physical Environment and Emergency Preparedness Requirements",
      },
      {
        authority: "NFPA",
        title: "Applicable Adopted Electrical, Life Safety, and Health Care Facility Codes",
      },
      {
        authority: "OSHA",
        title: "Electrical and Workplace Safety Requirements",
      },
    ],
    evidenceFrequency: "For every temporary utility arrangement",
    evidenceRetention:
      "Current survey cycle and according to project, incident, and risk-assessment retention requirements",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Authorization review, risk-assessment review, field inspection, monitoring-record review, and closure verification",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Temporary Utility Management",
    riskLevel: "High",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-011",
    slug: "utility-restoration-return-to-service",
    title: "Utility Restoration and Return-to-Service Verification",
    intent:
      "Utility systems are not returned to normal service until safe operation and required clinical functionality have been verified.",
    description:
      "The organization uses documented restoration criteria following utility interruption, repair, temporary service, system modification, contamination concern, or emergency response.",
    requirement:
      "Require verification of operational status, affected-space conditions, alarms, controls, safety features, clinical functionality, contamination controls, and stakeholder communication before formally returning an impaired utility to normal service.",
    surveyorLooksFor: [
      "Restoration responsibility is assigned",
      "The repaired or restored condition is identified",
      "Operational testing is completed",
      "Alarms and controls are verified",
      "Clinical functionality is confirmed",
      "Environmental conditions are assessed",
      "Contamination or flushing needs are addressed",
      "Temporary controls are removed",
      "Departments are notified of restoration",
      "Formal closure is documented",
    ],
    evidenceExamples: [
      "Utility restoration checklist",
      "Operational test results",
      "Alarm verification",
      "Environmental monitoring record",
      "Water flushing record",
      "Pressure restoration verification",
      "Clinical department approval",
      "Restoration notification",
      "Temporary control removal record",
      "Final closure documentation",
    ],
    commonFindings: [
      "Repairs are completed without operational testing",
      "Alarms are not verified",
      "Clinical functionality is assumed",
      "Temporary controls remain in place",
      "Departments are not notified of restoration",
      "Water or airflow systems are not flushed or verified",
      "The original incident cannot be linked to closure",
      "Return to service is undocumented",
    ],
    keywords: [
      "utility restoration",
      "return to service",
      "restoration verification",
      "utility restart checklist",
      "post repair testing",
      "utility operational verification",
      "system restoration",
      "utility closure",
      "post outage verification",
      "restoration notification",
    ],
    aiGuidance:
      "Map restoration checklists, testing results, alarm verification, environmental records, clinical approvals, notifications, temporary-control removal, and closure documentation. A completed repair ticket without functional verification should receive lower confidence.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Physical Environment Requirements",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
      {
        authority: "The Joint Commission",
        title: "Utility Systems Requirements",
      },
    ],
    evidenceFrequency:
      "Following every significant utility interruption, impairment, repair, temporary arrangement, or system modification",
    evidenceRetention:
      "Current survey cycle and according to incident, project, and utility documentation policies",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Restoration-record review, operational-test review, stakeholder confirmation, and closure verification",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Utility Restoration",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "HHS",
    chapter: "Utility Systems",
    code: "HHS-FAC-UTIL-012",
    slug: "utility-deficiency-program-oversight",
    title: "Utility Deficiency and Program Oversight",
    intent:
      "Utility deficiencies, outages, recurring failures, temporary controls, and unresolved risks are tracked, escalated, and evaluated through formal program oversight.",
    description:
      "The organization maintains visibility over utility risks by connecting incident records, shutdowns, deficiencies, contingency measures, restoration evidence, recurring failures, aging corrective actions, and leadership reporting.",
    requirement:
      "Maintain a coordinated process for tracking utility-system deficiencies and interruptions from identification through risk assessment, interim control, corrective action, operational verification, closure, trend analysis, and leadership escalation.",
    surveyorLooksFor: [
      "Utility deficiencies are centrally tracked",
      "Risk levels are assigned",
      "Interim controls are documented",
      "Responsible persons are identified",
      "Target completion dates are established",
      "Overdue high-risk issues are escalated",
      "Corrective actions receive verification",
      "Recurring failures are analyzed",
      "Temporary measures are monitored",
      "Leadership receives unresolved-risk information",
    ],
    evidenceExamples: [
      "Utility deficiency tracker",
      "Open-risk report",
      "Utility outage trend report",
      "Temporary-control log",
      "Corrective-action plan",
      "Restoration verification",
      "Environment-of-care committee minutes",
      "Leadership risk report",
      "Root-cause analysis",
      "Annual utility program evaluation",
    ],
    commonFindings: [
      "Utility risks are tracked in separate disconnected systems",
      "High-risk deficiencies remain overdue",
      "Interim controls are not documented",
      "Repairs are closed without operational verification",
      "Recurring failures are not trended",
      "Temporary measures become permanent",
      "Leadership is unaware of unresolved risks",
      "Annual evaluations do not address actual performance",
    ],
    keywords: [
      "utility deficiency tracker",
      "utility risk oversight",
      "utility corrective action",
      "utility outage trend",
      "open utility finding",
      "utility program evaluation",
      "temporary control log",
      "utility root cause",
      "utility leadership report",
      "utility compliance dashboard",
    ],
    aiGuidance:
      "Map deficiency trackers, risk reports, interim-control logs, corrective actions, restoration evidence, trend analyses, committee minutes, leadership reports, and annual evaluations showing complete utility-program oversight.",
    referencedAuthorities: [
      {
        authority: "CMS",
        title: "Hospital Conditions of Participation",
      },
      {
        authority: "The Joint Commission",
        title: "Utility Systems and Environment of Care Requirements",
      },
      {
        authority: "NFPA",
        citation: "NFPA 99",
        title: "Health Care Facilities Code",
      },
    ],
    evidenceFrequency:
      "Ongoing with formal program evaluation at least annually",
    evidenceRetention:
      "Current program records and prior survey-cycle evaluations, incidents, and corrective actions",
    responsibleRole: "Facilities Director",
    validationMethod:
      "Tracker review, risk-aging analysis, committee-record review, closure verification, and leadership interview",
    department: "Facilities",
    domain: "Utility Systems",
    category: "Utility Systems Management",
    riskLevel: "Critical",
    priority: 1,
    version: "1.0",
    status: "Active",
    isCustom: true,
  },
];