import type { HhsOperationalTopic } from "./types";

export const facilitiesOperationalTopics: HhsOperationalTopic[] = [
  {
    code: "HHS-FAC-FIRE-DOORS",
    slug: "fire-doors",
    name: "Fire Doors",
    description:
      "Management of fire door assemblies, including inventory, inspection, testing, maintenance, repairs, labeling, clearances, hardware, and documentation.",
    aiGuidance:
      "Map documents involving fire door inspections, annual testing, repair records, deficiency reports, inventories, labels, gaps, latching, closing, glazing, hardware, or field modifications.",
    domain: "Fire and Life Safety",
    category: "Fire Door Assemblies",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "fire door",
      "fire door inspection",
      "annual fire door inspection",
      "door assembly",
      "door gap",
      "positive latching",
      "self closing",
      "fire-rated door",
      "door label",
      "NFPA 80",
    ],
    evidenceExamples: [
      "Annual fire door inspection report",
      "Fire door inventory",
      "Fire door repair records",
      "Deficiency tracking log",
      "Door replacement documentation",
      "Completed corrective-action records",
    ],
    surveyorLooksFor: [
      "Complete inventory of required fire door assemblies",
      "Inspection completed at the required interval",
      "Deficiencies corrected promptly",
      "Doors close and latch without assistance",
      "Required labels remain visible and legible",
      "Repairs and field modifications are properly documented",
    ],
    commonFindings: [
      "Excessive door clearances",
      "Doors fail to latch",
      "Damaged or missing labels",
      "Unapproved field modifications",
      "Obstructed or wedged-open doors",
      "Inspection deficiencies remain unresolved",
    ],
    evidenceFrequency: "At least annually and after significant repair",
    evidenceRetention: "Current inspection cycle and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review and physical inspection",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-FIRE-DRILLS",
    slug: "fire-drills",
    name: "Fire Drills",
    description:
      "Planning, conducting, documenting, evaluating, and improving fire-response drills across required shifts, locations, and operating conditions.",
    aiGuidance:
      "Map fire drill reports, attendance records, observer evaluations, response critiques, corrective actions, drill schedules, and fire-response education.",
    domain: "Fire and Life Safety",
    category: "Emergency Response",
    riskLevel: "High",
    priority: 1,
    keywords: [
      "fire drill",
      "RACE",
      "PASS",
      "fire response",
      "drill report",
      "fire alarm drill",
      "staff response",
      "evacuation drill",
    ],
    evidenceExamples: [
      "Fire drill report",
      "Fire drill schedule",
      "Attendance roster",
      "Observer evaluation",
      "Corrective-action plan",
      "Fire-response training record",
    ],
    surveyorLooksFor: [
      "Drills conducted at required intervals",
      "Coverage of required shifts and locations",
      "Staff knowledge of fire-response duties",
      "Evaluation of drill performance",
      "Corrective actions for identified weaknesses",
      "Evidence of follow-up and improvement",
    ],
    commonFindings: [
      "Drills do not cover all shifts",
      "Documentation lacks evaluation",
      "Staff cannot describe fire-response duties",
      "Corrective actions are not completed",
      "Drills are overly predictable",
      "Required locations are omitted",
    ],
    evidenceFrequency: "According to occupancy, shift, and regulatory requirements",
    evidenceRetention: "Current year and prior survey cycle",
    responsibleRole: "Safety Officer",
    validationMethod: "Document review and staff interview",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-FIRE-ALARM",
    slug: "fire-alarm-systems",
    name: "Fire Alarm Systems",
    description:
      "Inspection, testing, maintenance, impairment management, and documentation for fire alarm and emergency communication systems.",
    aiGuidance:
      "Map fire alarm inspection reports, testing records, panel reports, device inventories, notification appliance tests, impairment records, repair documentation, and acceptance testing.",
    domain: "Fire and Life Safety",
    category: "Fire Alarm and Detection",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "fire alarm",
      "smoke detector",
      "heat detector",
      "notification appliance",
      "pull station",
      "fire alarm panel",
      "alarm testing",
      "NFPA 72",
      "alarm impairment",
    ],
    evidenceExamples: [
      "Fire alarm inspection report",
      "Annual system test",
      "Semiannual testing record",
      "Device inventory",
      "Repair report",
      "Impairment documentation",
    ],
    surveyorLooksFor: [
      "Testing completed at required frequencies",
      "Complete device coverage",
      "Deficiencies corrected",
      "Impairments managed and communicated",
      "Testing performed by qualified personnel",
      "Records identify devices, results, and dates",
    ],
    commonFindings: [
      "Missing devices from test records",
      "Overdue testing",
      "Unresolved alarm deficiencies",
      "Incomplete impairment documentation",
      "Testing reports lack identifiable locations",
      "Required notifications are not documented",
    ],
    evidenceFrequency: "At required inspection and testing intervals",
    evidenceRetention: "Current records and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review and system observation",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-SPRINKLER",
    slug: "sprinkler-systems",
    name: "Automatic Sprinkler Systems",
    description:
      "Inspection, testing, maintenance, impairment management, and documentation for sprinkler systems, valves, waterflow devices, piping, and associated components.",
    aiGuidance:
      "Map sprinkler inspection reports, valve inspections, flow tests, main drain tests, obstruction investigations, impairment records, repair documentation, and NFPA 25 service reports.",
    domain: "Fire and Life Safety",
    category: "Fire Suppression",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "sprinkler",
      "sprinkler inspection",
      "control valve",
      "waterflow",
      "main drain test",
      "NFPA 25",
      "sprinkler impairment",
      "fire suppression",
      "tamper switch",
    ],
    evidenceExamples: [
      "Sprinkler inspection report",
      "Control-valve inspection",
      "Main drain test",
      "Waterflow alarm test",
      "Impairment permit",
      "Repair and restoration record",
    ],
    surveyorLooksFor: [
      "Required inspections and tests are current",
      "Valves are accessible, supervised, and secured",
      "Deficiencies are corrected promptly",
      "Impairments are managed",
      "Storage maintains required sprinkler clearance",
      "System changes are properly documented",
    ],
    commonFindings: [
      "Blocked sprinkler clearance",
      "Unsecured or inaccessible valves",
      "Missing inspection documentation",
      "Overdue testing",
      "Improper storage beneath sprinklers",
      "Unresolved deficiencies",
    ],
    evidenceFrequency: "At required inspection, testing, and maintenance intervals",
    evidenceRetention: "Current records and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review and physical inspection",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-EGRESS",
    slug: "means-of-egress",
    name: "Means of Egress",
    description:
      "Maintenance of accessible, unobstructed, adequately illuminated, and properly marked paths of travel to approved exits.",
    aiGuidance:
      "Map exit inspections, corridor-rounding records, emergency-light testing, exit-sign testing, obstruction findings, corrective actions, and egress-related policies.",
    domain: "Fire and Life Safety",
    category: "Means of Egress",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "means of egress",
      "exit",
      "exit access",
      "corridor obstruction",
      "exit sign",
      "emergency lighting",
      "path of travel",
      "blocked exit",
    ],
    evidenceExamples: [
      "Egress inspection checklist",
      "Exit-sign testing record",
      "Emergency-light testing record",
      "Safety-rounding report",
      "Corrective-action record",
      "Door and corridor inspection",
    ],
    surveyorLooksFor: [
      "Required corridors and exits remain unobstructed",
      "Exit signs are visible and functional",
      "Emergency lighting is tested",
      "Doors operate as required",
      "Storage does not reduce required egress width",
      "Deficiencies are corrected promptly",
    ],
    commonFindings: [
      "Equipment stored in corridors",
      "Blocked exits",
      "Nonfunctioning exit signs",
      "Emergency lights fail testing",
      "Improper door locking",
      "Temporary construction affects egress without mitigation",
    ],
    evidenceFrequency: "Ongoing monitoring with periodic documented inspection",
    evidenceRetention: "Current inspection cycle and survey cycle",
    responsibleRole: "Safety Officer",
    validationMethod: "Physical inspection and document review",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-EPSS",
    slug: "emergency-power",
    name: "Emergency Power Systems",
    description:
      "Inspection, testing, maintenance, fuel management, transfer testing, load performance, and reliability of emergency power supply systems.",
    aiGuidance:
      "Map generator tests, ATS tests, load-bank tests, fuel records, maintenance reports, failure investigations, preventive-maintenance records, and emergency-power policies.",
    domain: "Utility Systems",
    category: "Emergency Electrical Power",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "generator",
      "emergency power",
      "EPSS",
      "automatic transfer switch",
      "ATS",
      "load bank",
      "NFPA 110",
      "generator test",
      "fuel quality",
      "emergency electrical",
    ],
    evidenceExamples: [
      "Monthly generator test",
      "ATS testing record",
      "Annual load-bank test",
      "Fuel quality report",
      "Generator preventive-maintenance record",
      "Emergency power failure investigation",
    ],
    surveyorLooksFor: [
      "Testing completed at required intervals",
      "Transfer times and operating parameters documented",
      "Required load conditions achieved",
      "Failures and deficiencies corrected",
      "Fuel supply and fuel quality are managed",
      "Emergency power equipment is maintained and accessible",
    ],
    commonFindings: [
      "Incomplete monthly test documentation",
      "Insufficient load during testing",
      "ATS devices omitted from test records",
      "Overdue repairs",
      "Fuel quality not evaluated",
      "Failure to document corrective action after unsuccessful tests",
    ],
    evidenceFrequency: "Monthly, annually, and at other required intervals",
    evidenceRetention: "Current records and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review, equipment observation, and staff interview",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-MED-GAS",
    slug: "medical-gas-and-vacuum",
    name: "Medical Gas and Vacuum Systems",
    description:
      "Inspection, testing, maintenance, labeling, alarm management, valve control, source equipment, and documentation for medical gas and vacuum systems.",
    aiGuidance:
      "Map medical gas inspection reports, alarm tests, zone-valve records, master alarm tests, source-equipment maintenance, cylinder-manifold inspections, repairs, and certification reports.",
    domain: "Utility Systems",
    category: "Medical Gas and Vacuum",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "medical gas",
      "medical vacuum",
      "zone valve",
      "master alarm",
      "area alarm",
      "oxygen",
      "nitrous oxide",
      "medical air",
      "NFPA 99",
      "gas inspection",
    ],
    evidenceExamples: [
      "Annual medical gas inspection",
      "Medical gas alarm test",
      "Zone-valve inspection",
      "Source-equipment preventive maintenance",
      "Medical gas certification",
      "Repair and verification report",
    ],
    surveyorLooksFor: [
      "System components are properly identified",
      "Alarms and valves are accessible",
      "Inspection and testing are current",
      "Deficiencies are corrected",
      "Staff know emergency shutoff responsibilities",
      "Modifications are tested and certified",
    ],
    commonFindings: [
      "Inaccessible zone valves",
      "Missing valve-area labels",
      "Overdue alarm testing",
      "Unresolved inspection deficiencies",
      "Improper cylinder storage",
      "System modifications lack verification",
    ],
    evidenceFrequency: "At required inspection, testing, and maintenance intervals",
    evidenceRetention: "Current records, prior survey cycle, and system certification records",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review, physical inspection, and staff interview",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-HVAC",
    slug: "hvac-systems",
    name: "HVAC Systems",
    description:
      "Operation, monitoring, maintenance, and corrective action for heating, ventilation, air-conditioning, pressure relationships, temperature, humidity, filtration, and air quality.",
    aiGuidance:
      "Map HVAC preventive-maintenance records, temperature and humidity logs, pressure-monitoring reports, air-balance reports, filter-change records, BAS trend reports, and corrective actions.",
    domain: "Utility Systems",
    category: "Heating, Ventilation, and Air Conditioning",
    riskLevel: "High",
    priority: 1,
    keywords: [
      "HVAC",
      "temperature",
      "humidity",
      "air pressure",
      "air changes",
      "negative pressure",
      "positive pressure",
      "filter change",
      "air balance",
      "ASHRAE 170",
    ],
    evidenceExamples: [
      "HVAC preventive-maintenance record",
      "Temperature and humidity log",
      "Pressure-relationship monitoring report",
      "Air-balance report",
      "Filter replacement record",
      "Corrective-action documentation",
    ],
    surveyorLooksFor: [
      "Critical areas maintain required environmental conditions",
      "Excursions are identified and addressed",
      "Monitoring systems are functional",
      "Preventive maintenance is current",
      "Airflow and pressure relationships are validated",
      "Corrective actions include clinical notification when appropriate",
    ],
    commonFindings: [
      "Unresolved temperature or humidity excursions",
      "Pressure relationships are not monitored",
      "Missing documentation of corrective action",
      "Overdue preventive maintenance",
      "Air-balance reports are outdated",
      "Critical alarms are disabled or ignored",
    ],
    evidenceFrequency: "Continuous monitoring where required with scheduled maintenance",
    evidenceRetention: "Current records and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review, BAS review, and physical observation",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-WATER",
    slug: "water-management",
    name: "Water Management",
    description:
      "Management of building water systems to reduce waterborne pathogen risk and maintain safe water quality, temperature, distribution, and system performance.",
    aiGuidance:
      "Map water management plans, committee records, Legionella risk assessments, water testing, flushing logs, temperature monitoring, corrective actions, and validation reports.",
    domain: "Utility Systems",
    category: "Water Safety",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "water management",
      "Legionella",
      "water safety",
      "flushing",
      "water temperature",
      "water testing",
      "building water system",
      "ASHRAE 188",
      "waterborne pathogen",
    ],
    evidenceExamples: [
      "Water management plan",
      "Legionella risk assessment",
      "Water-management committee minutes",
      "Flushing log",
      "Water-temperature monitoring",
      "Water-testing results",
    ],
    surveyorLooksFor: [
      "A multidisciplinary water-management program",
      "Complete building-water-system diagrams",
      "Defined control limits",
      "Monitoring and corrective-action procedures",
      "Validation and verification activities",
      "Response to construction, stagnation, or water disruption",
    ],
    commonFindings: [
      "Incomplete system diagrams",
      "Control limits are not defined",
      "Monitoring is inconsistent",
      "Corrective actions are not documented",
      "Low-use outlets are not addressed",
      "Construction and water interruptions are not assessed",
    ],
    evidenceFrequency: "Ongoing according to the water-management plan",
    evidenceRetention: "Current program records and prior survey cycle",
    responsibleRole: "Water Management Program Leader",
    validationMethod: "Document review, system observation, and staff interview",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-UTILITY-FAILURE",
    slug: "utility-failure-response",
    name: "Utility Failure Response",
    description:
      "Preparedness, response, communication, mitigation, recovery, and after-action review for failures of electricity, water, HVAC, medical gas, communications, sewer, fuel, and other utilities.",
    aiGuidance:
      "Map utility-failure procedures, outage response plans, emergency shutdown procedures, event reports, communication logs, after-action reviews, and corrective-action plans.",
    domain: "Utility Systems",
    category: "Utility Failure and Continuity",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "utility failure",
      "power outage",
      "water outage",
      "HVAC failure",
      "medical gas failure",
      "utility interruption",
      "emergency shutdown",
      "business continuity",
      "after-action review",
    ],
    evidenceExamples: [
      "Utility failure response plan",
      "Power interruption procedure",
      "Water outage procedure",
      "HVAC failure procedure",
      "Outage communication record",
      "After-action review",
    ],
    surveyorLooksFor: [
      "Defined response procedures for critical utility failures",
      "Clear notification and escalation pathways",
      "Clinical impact assessment",
      "Alternative sources or mitigation strategies",
      "Recovery and return-to-service procedures",
      "Post-event review and corrective action",
    ],
    commonFindings: [
      "Procedures do not identify responsible roles",
      "Clinical departments are not included in planning",
      "Alternative supply strategies are unclear",
      "Events are not reviewed after resolution",
      "Shutdown procedures are outdated",
      "Communication expectations are undefined",
    ],
    evidenceFrequency: "Reviewed annually and after significant events or changes",
    evidenceRetention: "Current plan, event records, and prior survey cycle",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review, staff interview, and event-record review",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-ILSM",
    slug: "interim-life-safety-measures",
    name: "Interim Life Safety Measures",
    description:
      "Evaluation and implementation of temporary measures when construction, deficiencies, impairments, or other conditions compromise life-safety features.",
    aiGuidance:
      "Map ILSM assessments, interim-measure checklists, impairment records, fire-watch documentation, construction assessments, training records, and closure documentation.",
    domain: "Fire and Life Safety",
    category: "Interim Life Safety",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "interim life safety measures",
      "ILSM",
      "fire watch",
      "life safety impairment",
      "construction impairment",
      "temporary measure",
      "egress impairment",
      "fire protection impairment",
    ],
    evidenceExamples: [
      "ILSM assessment",
      "Interim life-safety checklist",
      "Fire-watch log",
      "Staff education record",
      "Impairment notification",
      "ILSM termination documentation",
    ],
    surveyorLooksFor: [
      "Assessment completed when life-safety features are impaired",
      "Measures match the level of risk",
      "Required inspections and surveillance occur",
      "Staff and occupants receive appropriate communication",
      "Measures remain active until full restoration",
      "Closure is formally documented",
    ],
    commonFindings: [
      "ILSM assessment not completed",
      "Measures do not address the identified risk",
      "Fire-watch documentation is incomplete",
      "ILSM is discontinued before restoration",
      "Staff are unaware of temporary precautions",
      "Construction changes are not reassessed",
    ],
    evidenceFrequency: "Whenever life-safety features are impaired",
    evidenceRetention: "Project or impairment duration plus prior survey cycle",
    responsibleRole: "Life Safety Specialist or Safety Officer",
    validationMethod: "Document review and physical inspection",
    status: "Active",
    isCustom: false,
  },
  {
    code: "HHS-FAC-CONSTRUCTION",
    slug: "construction-risk-management",
    name: "Construction Risk Management",
    description:
      "Assessment and control of infection, life-safety, utility, dust, noise, vibration, security, access, and operational risks created by construction, renovation, demolition, and disruptive maintenance.",
    aiGuidance:
      "Map preconstruction risk assessments, ICRA documents, ILSM assessments, permits, barrier inspections, negative-air logs, shutdown plans, construction-rounding records, and clearance documentation.",
    domain: "Construction and Renovation",
    category: "Project Risk Management",
    riskLevel: "Critical",
    priority: 1,
    keywords: [
      "construction risk",
      "preconstruction risk assessment",
      "PCRA",
      "ICRA",
      "renovation",
      "demolition",
      "barrier inspection",
      "negative air",
      "construction permit",
      "disruptive maintenance",
    ],
    evidenceExamples: [
      "Preconstruction risk assessment",
      "Infection control risk assessment",
      "ILSM assessment",
      "Construction barrier inspection",
      "Utility shutdown plan",
      "Project completion clearance",
    ],
    surveyorLooksFor: [
      "Risk assessment completed before work begins",
      "Mitigation measures are implemented",
      "Construction barriers are maintained",
      "Utility impacts are coordinated",
      "Changes in scope are reassessed",
      "Final clearance occurs before occupancy",
    ],
    commonFindings: [
      "Work begins before risk assessment",
      "Barrier inspections are incomplete",
      "Project scope changes are not reassessed",
      "Dust or negative-air controls are ineffective",
      "Utility shutdowns are poorly coordinated",
      "Final clearance is not documented",
    ],
    evidenceFrequency: "Before each applicable project and as conditions change",
    evidenceRetention: "Project duration plus organizational retention period",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review and project-site observation",
    status: "Active",
    isCustom: false,
  },
];