import type { HhsCoreStandard } from "../types";
/**
 * HHS-developed survey-readiness controls aligned with the 2026
 * Joint Commission Physical Environment framework for hospitals
 * and critical access hospitals.
 *
 * These records are original HHS operational controls. They are not
 * reproductions of proprietary Joint Commission standards or Elements
 * of Performance. Official citations should be connected separately
 * through appropriately licensed or customer-provided source material.
 */
export const jointCommissionPhysicalEnvironment: HhsCoreStandard[] = [
  {
    accreditor: "The Joint Commission",
    chapter: "Physical Environment",
    code: "HHS-TJC-PE-GOV-001",
    slug: "hhs-tjc-pe-physical-environment-oversight",
    title: "Physical Environment Program Oversight",
    intent:
      "The organization maintains coordinated oversight of risks associated with its buildings, systems, equipment, operations, and physical environment.",
    description:
      "A formal oversight process assigns responsibility, establishes reporting relationships, monitors performance, and communicates significant physical-environment risks to organizational leadership.",
    requirement:
      "Maintain a documented physical-environment oversight process that defines responsibilities, performance measures, risk-escalation pathways, and leadership reporting expectations.",
    surveyorLooksFor: [
      "Defined responsibility for physical-environment oversight",
      "A documented reporting and governance structure",
      "Routine review of physical-environment performance",
      "Escalation of significant or unresolved risks",
      "Leadership involvement in resource decisions",
      "Follow-up on corrective actions",
    ],
    evidenceExamples: [
      "Physical environment management plan",
      "Safety or environment-of-care committee charter",
      "Committee meeting minutes",
      "Leadership reports",
      "Physical environment dashboard",
      "Corrective-action status reports",
    ],
    commonFindings: [
      "Responsibilities are not clearly assigned",
      "Performance information is not reported to leadership",
      "High-risk deficiencies are not escalated",
      "Committee minutes document discussion but not action",
      "Resource needs are identified without resolution",
    ],
    keywords: [
      "physical environment",
      "environment of care",
      "leadership oversight",
      "safety committee",
      "governance",
      "facilities oversight",
      "risk escalation",
    ],
    aiGuidance:
      "Map governance plans, committee records, leadership reports, and dashboards that demonstrate coordinated oversight of physical-environment risks. Do not map an isolated work order unless it shows broader program oversight.",
    evidenceFrequency: "Ongoing with periodic leadership reporting",
    evidenceRetention: "Current survey cycle and prior annual review",
    responsibleRole: "Safety Officer or Facilities Director",
    validationMethod: "Document review and leadership interview",
    referencedAuthorities: [
      {
        authority: "The Joint Commission",
        title: "Physical Environment",
        edition: "2026",
        notes:
          "HHS operational control aligned to the current hospital and critical access hospital Physical Environment framework.",
      },
    ],
    department: "Facilities",
    domain: "Program Governance",
    category: "Oversight",
    riskLevel: "High",
    priority: 1,
    version: "2026",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "The Joint Commission",
    chapter: "Physical Environment",
    code: "HHS-TJC-PE-RM-001",
    slug: "hhs-tjc-pe-risk-assessment",
    title: "Physical Environment Risk Assessment",
    intent:
      "The organization proactively identifies and prioritizes environmental conditions that could harm patients, staff, visitors, or healthcare operations.",
    description:
      "Physical-environment risks are evaluated using inspections, incidents, equipment history, utility performance, regulatory findings, construction activities, and operational changes.",
    requirement:
      "Conduct and document periodic physical-environment risk assessments and implement prioritized mitigation measures for identified hazards.",
    surveyorLooksFor: [
      "A defined risk-assessment methodology",
      "Identification of affected locations and populations",
      "Risk ranking based on likelihood and consequence",
      "Assigned mitigation actions",
      "Target completion dates",
      "Reassessment after significant changes",
    ],
    evidenceExamples: [
      "Physical environment risk assessment",
      "Hazard assessment",
      "Safety-rounding reports",
      "Risk register",
      "Corrective-action tracker",
      "Interim mitigation plan",
    ],
    commonFindings: [
      "Risks are listed without prioritization",
      "Corrective actions lack responsible owners",
      "Overdue risks have no interim mitigation",
      "Assessments are not updated after operational changes",
      "Repeated findings are not treated as systemic risks",
    ],
    keywords: [
      "risk assessment",
      "physical environment risk",
      "hazard assessment",
      "risk register",
      "safety risk",
      "mitigation plan",
      "environmental hazard",
    ],
    aiGuidance:
      "Map documents demonstrating a systematic evaluation and prioritization of physical-environment hazards. Routine checklists without risk analysis should receive lower confidence.",
    evidenceFrequency: "At least annually and after significant changes",
    evidenceRetention: "Current assessment and prior survey cycle",
    responsibleRole: "Safety Officer",
    validationMethod: "Document review, observation, and staff interview",
    referencedAuthorities: [
      {
        authority: "The Joint Commission",
        title: "Physical Environment",
        edition: "2026",
      },
    ],
    department: "Facilities",
    domain: "Risk Management",
    category: "Risk Assessment",
    riskLevel: "High",
    priority: 1,
    version: "2026",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "The Joint Commission",
    chapter: "Physical Environment",
    code: "HHS-TJC-PE-INS-001",
    slug: "hhs-tjc-pe-environmental-rounding",
    title: "Physical Environment Rounding",
    intent:
      "The organization routinely inspects patient-care and support areas to identify unsafe conditions before they result in harm.",
    description:
      "Interdisciplinary rounds evaluate safety, security, hazardous materials, fire protection, means of egress, equipment, utilities, construction conditions, and general building risks.",
    requirement:
      "Conduct documented physical-environment rounds at established intervals and track identified deficiencies through verified completion.",
    surveyorLooksFor: [
      "A defined rounding schedule",
      "Coverage of patient-care and nonpatient areas",
      "Participation by appropriate disciplines",
      "Documented observations and findings",
      "Assigned corrective actions",
      "Verified closure of deficiencies",
    ],
    evidenceExamples: [
      "Physical environment rounding checklist",
      "Completed inspection reports",
      "Rounding schedule",
      "Deficiency log",
      "Related work orders",
      "Closure-verification records",
    ],
    commonFindings: [
      "Required areas are omitted from rounds",
      "Rounds are inconsistently completed",
      "Findings remain open without escalation",
      "Repeated deficiencies are not analyzed",
      "Closure is recorded without verification",
    ],
    keywords: [
      "physical environment rounds",
      "environment of care rounds",
      "EOC rounds",
      "safety rounds",
      "facility inspection",
      "deficiency log",
      "rounding checklist",
    ],
    aiGuidance:
      "Map completed inspection and rounding records with identifiable dates, locations, findings, responsible parties, and closure evidence. Blank templates should not be considered implementation evidence.",
    evidenceFrequency:
      "At intervals established by organizational policy and area risk",
    evidenceRetention: "Current survey cycle or organizational policy",
    responsibleRole: "Safety Officer",
    validationMethod: "Document review and physical observation",
    referencedAuthorities: [
      {
        authority: "The Joint Commission",
        title: "Physical Environment",
        edition: "2026",
      },
    ],
    department: "Facilities",
    domain: "Inspection and Monitoring",
    category: "Rounding",
    riskLevel: "High",
    priority: 1,
    version: "2026",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "The Joint Commission",
    chapter: "Physical Environment",
    code: "HHS-TJC-PE-CA-001",
    slug: "hhs-tjc-pe-corrective-action-management",
    title: "Physical Environment Corrective-Action Management",
    intent:
      "Physical-environment deficiencies are corrected promptly, tracked consistently, and prevented from recurring.",
    description:
      "A centralized process assigns owners, establishes risk-based due dates, documents interim controls, verifies completion, and escalates overdue findings.",
    requirement:
      "Track physical-environment deficiencies from identification through verified closure and establish interim risk-reduction measures when immediate correction is not possible.",
    surveyorLooksFor: [
      "A consolidated deficiency-tracking process",
      "Assigned responsible individuals",
      "Risk-based completion dates",
      "Interim mitigation for delayed correction",
      "Evidence supporting completion",
      "Escalation of overdue high-risk findings",
    ],
    evidenceExamples: [
      "Corrective-action log",
      "Work-order reports",
      "Interim mitigation documentation",
      "Repair records",
      "Completion photographs",
      "Committee follow-up reports",
    ],
    commonFindings: [
      "High-risk deficiencies remain overdue",
      "No interim controls are documented",
      "Completion is not independently verified",
      "Repeat deficiencies are treated as isolated events",
      "Corrective-action records are fragmented",
    ],
    keywords: [
      "corrective action",
      "deficiency tracking",
      "work order",
      "interim mitigation",
      "action plan",
      "closure verification",
      "overdue finding",
    ],
    aiGuidance:
      "Map documentation that demonstrates assignment, mitigation, repair, completion, and verification. A work order that remains open should not satisfy the control.",
    evidenceFrequency: "Ongoing",
    evidenceRetention: "Current survey cycle or organizational policy",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review and physical verification",
    referencedAuthorities: [
      {
        authority: "The Joint Commission",
        title: "Physical Environment",
        edition: "2026",
      },
    ],
    department: "Facilities",
    domain: "Corrective Action",
    category: "Deficiency Management",
    riskLevel: "High",
    priority: 1,
    version: "2026",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "The Joint Commission",
    chapter: "Physical Environment",
    code: "HHS-TJC-PE-CON-001",
    slug: "hhs-tjc-pe-construction-risk-management",
    title: "Construction and Renovation Risk Management",
    intent:
      "Construction, renovation, demolition, and disruptive maintenance activities are controlled to protect patients, staff, visitors, and healthcare operations.",
    description:
      "Project planning evaluates infection control, life safety, utilities, dust, noise, vibration, security, traffic, patient movement, emergency access, and adjacent operations.",
    requirement:
      "Complete and implement a documented project risk assessment before construction, renovation, demolition, or disruptive maintenance begins and reassess when project conditions change.",
    surveyorLooksFor: [
      "A completed preconstruction risk assessment",
      "Defined infection-control precautions",
      "Assessment of life-safety impacts",
      "Evaluation of utility interruptions",
      "Ongoing project-area inspections",
      "Final clearance before occupancy or return to service",
    ],
    evidenceExamples: [
      "Preconstruction risk assessment",
      "Infection control risk assessment",
      "Interim life-safety assessment",
      "Construction inspection reports",
      "Barrier inspection logs",
      "Project completion clearance",
    ],
    commonFindings: [
      "Risk assessment is completed after work begins",
      "Project scope changes are not reassessed",
      "Temporary barriers are poorly maintained",
      "Utility impacts are not coordinated",
      "Final environmental clearance is not documented",
    ],
    keywords: [
      "preconstruction risk assessment",
      "PCRA",
      "ICRA",
      "construction risk",
      "renovation",
      "interim life safety",
      "barrier inspection",
      "disruptive maintenance",
    ],
    aiGuidance:
      "Map project-specific assessments, permits, inspection logs, and clearance documentation. Generic construction policies alone do not demonstrate project-level implementation.",
    evidenceFrequency:
      "Before each applicable project and whenever conditions change",
    evidenceRetention: "Project duration plus organizational retention period",
    responsibleRole: "Facilities Director",
    validationMethod: "Document review and project-area observation",
    referencedAuthorities: [
      {
        authority: "The Joint Commission",
        title: "Physical Environment",
        edition: "2026",
      },
      {
        authority: "Facility Guidelines Institute",
        notes: "Applicable planning and construction guidance",
      },
    ],
    department: "Facilities",
    domain: "Construction Risk",
    category: "Project Risk Assessment",
    riskLevel: "Critical",
    priority: 1,
    version: "2026",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "The Joint Commission",
    chapter: "Physical Environment",
    code: "HHS-TJC-PE-EDU-001",
    slug: "hhs-tjc-pe-staff-education",
    title: "Physical Environment Safety Education",
    intent:
      "Staff understand the physical-environment risks relevant to their roles and know how to report and respond to unsafe conditions.",
    description:
      "Orientation and recurring education address hazard reporting, emergency actions, physical-environment responsibilities, and role-specific risks.",
    requirement:
      "Provide and document initial and recurring physical-environment safety education appropriate to staff duties and identified organizational risks.",
    surveyorLooksFor: [
      "Physical-environment content in orientation",
      "Role-specific training",
      "Recurring education",
      "Competency or understanding verification",
      "Complete training records",
      "Education following significant changes or events",
    ],
    evidenceExamples: [
      "Orientation materials",
      "Annual education modules",
      "Attendance records",
      "Competency checklists",
      "Post-training assessments",
      "Department-specific safety education",
    ],
    commonFindings: [
      "Training is generic rather than role-specific",
      "Contract personnel are omitted",
      "Completion records are incomplete",
      "Education is not updated after policy changes",
      "Staff cannot describe expected emergency actions",
    ],
    keywords: [
      "physical environment education",
      "safety training",
      "orientation",
      "annual education",
      "competency",
      "hazard reporting",
      "staff safety",
    ],
    aiGuidance:
      "Map training records only when the content addresses physical-environment risks, responsibilities, or emergency actions. A roster without identifiable training content should receive lower confidence.",
    evidenceFrequency: "At orientation and recurring thereafter",
    evidenceRetention: "Per personnel and training-record policy",
    responsibleRole: "Safety Officer",
    validationMethod: "Training-record review and staff interview",
    referencedAuthorities: [
      {
        authority: "The Joint Commission",
        title: "Physical Environment",
        edition: "2026",
      },
    ],
    department: "Facilities",
    domain: "Education",
    category: "Staff Training",
    riskLevel: "Moderate",
    priority: 2,
    version: "2026",
    status: "Active",
    isCustom: true,
  },
  {
    accreditor: "The Joint Commission",
    chapter: "Physical Environment",
    code: "HHS-TJC-PE-EVAL-001",
    slug: "hhs-tjc-pe-annual-program-evaluation",
    title: "Annual Physical Environment Program Evaluation",
    intent:
      "Leadership evaluates whether the physical-environment program remains effective and adequately addresses organizational risks.",
    description:
      "The annual evaluation summarizes objectives, incidents, inspections, equipment and utility performance, corrective actions, trends, and improvement priorities.",
    requirement:
      "Complete and document an annual evaluation of physical-environment performance and report significant results, risks, and improvement priorities to organizational leadership.",
    surveyorLooksFor: [
      "Evaluation of annual objectives",
      "Analysis of performance data",
      "Review of incidents and recurring trends",
      "Assessment of corrective-action effectiveness",
      "Identification of improvement priorities",
      "Documented leadership review",
    ],
    evidenceExamples: [
      "Annual physical environment evaluation",
      "Annual safety report",
      "Performance indicator summary",
      "Committee minutes",
      "Leadership presentation",
      "Annual improvement plan",
    ],
    commonFindings: [
      "The evaluation only lists completed activities",
      "Objectives are not measurable",
      "Performance trends are not analyzed",
      "Leadership review is not documented",
      "Improvement priorities are not established",
    ],
    keywords: [
      "annual physical environment evaluation",
      "annual safety evaluation",
      "annual EOC report",
      "annual review",
      "safety performance",
      "leadership report",
      "performance evaluation",
    ],
    aiGuidance:
      "Map annual reports that evaluate program effectiveness using performance results and trends. Routine meeting minutes alone should not satisfy the control unless they contain the required annual analysis.",
    evidenceFrequency: "Annually",
    evidenceRetention: "Current evaluation and prior survey cycle",
    responsibleRole: "Safety Officer",
    validationMethod: "Document review and leadership interview",
    referencedAuthorities: [
      {
        authority: "The Joint Commission",
        title: "Physical Environment",
        edition: "2026",
      },
    ],
    department: "Facilities",
    domain: "Program Evaluation",
    category: "Annual Evaluation",
    riskLevel: "High",
    priority: 1,
    version: "2026",
    status: "Active",
    isCustom: true,
  },
];